### PR TITLE
Replaced `rcp_static_cast<>()->` with `down_cast<>().`

### PR DESCRIPTION
**Pull request by ShikharJ**
Relevant: #1155

### CODE REVIEW

**Comment by ShikharJ** [comment]
ping @certik

**Comment by certik** [comment]
Sorry, I need to think about this a bit. The previous way should be safe, but this might not be in all cases. @isuruf if you like it, we can merge it.

**Comment by ShikharJ** [comment]
@isuruf Could you please take a look at this also?

**Comment by certik** [comment]
It's fine with me if @isuruf gives this +1.

**Pull request merged**
