### PR TITLE
Add constructors for Expression

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
You should add more tests for conversion to `RCP<const Basic>`. Something like:
```c++
Expression e1 = ...
RCP<const Basic> r1 = e1;
const RCP<const Basic> r2 = e1;
r1 = sin(e1);
r1 = sin(e1+1);
```
And so on.

**Comment by certik** [comment]
@isuruf actually, I just noticed that the `expression.h` implements:
```c++
inline Expression pow(const Expression &base, const Expression &exp)
{
    return pow(base.get_basic(), exp.get_basic());
}
```
So another option is to simply implement these for all our functions like `mul`, `sin`, ...

**Comment by certik** [comment]
So we might not want to allow implicit conversion to `RCP<const Basic>` after all, for similar reasons that Piranha or Teuchos::Ptr don't allow implicit conversions from int or a pointer.

@bluescarni what do you think? What's the best way forward here?

**Comment by bluescarni** [comment]
@certik I tend to avoid implicit conversions whenever possible, but in order to have an informed opinion in this specific case I'd need to know how you intend to use them. Is it to avoid writing overloads for ``pow()``, ``mult()``, etc. that take ``Expression`` as input rather than ``RCP<const Basic>``?

**Comment by certik** [comment]
@bluescarni I think that was our original intent why @isuruf wrote the PR. Until I just saw that you can just overload `pow`, `sin`, etc. to achieve the same, without implicit conversion, which seems like a much cleaner solution to me. We can write macros to generate the boilerplate code of the type:
```
inline Expression X(const Expression &A, const Expression &B)
{
    return X(A.get_basic(), B.get_basic());
}
```

**Comment by bluescarni** [comment]
@certik Yes my reaction would be that I'd rather do that instead of using implicit conversion. You could also define a single template ``pow()`` function and then relay the implementation to different specialised functors, but I know you are not a fan of templates :)

**Comment by isuruf** [comment]
Removed implicit conversions

**Comment by rwst** [comment]
I would like to have this, and it looks fine.

**Pull request merged**
