### PR TITLE
Update clang format version to 11

### PR DESCRIPTION
**Pull request by lkeegan**
- many users don't have a convenient way to install the previously used version (3.8)

which version to use?

- conda forge uses 11: https://anaconda.org/conda-forge/clangdev
- brew on macos uses 12: https://formulae.brew.sh/formula/clang-format
- ubuntu 20.04 uses 10, 20.10 uses 11, 21.04 uses 12
  - but 11 & 12 are easily installable for all ubuntu versions from https://apt.llvm.org/
- ...?

(see first commit for actual changes, second commit is just running clang-format)

### CODE REVIEW

**Comment by rikardn** [comment]
I like the idea of using a newer version of the formatter. Are you using the default options? I like most of the new ways it formats better, but a few looks worse. I still think using the default is good despite my objection.

Would it be possible to make the formatting automatic in some way? E.g. have the bot automatically change the formatting for a PR or having the formatting in cmake in some way. (I guess setting up a pre-commit hook in github would work, but I haven't gotten around to do that, partly because of the formatter version)

**Comment by lkeegan** [comment]
@rikardn The options are already specified here: https://github.com/symengine/symengine/blob/master/.clang-format
I haven't changed anything there, but each version of clang-format formats things a little differently (although 11 and 12 give the same output on the current symengine codebase)

Personally I don't like the idea of the bot making commits, but adding documentation on how to install clang-format and set up the git pre-commit hook would certainly be good! (see #1587, https://github.com/symengine/symengine/pull/1716#issuecomment-737721345)

**Comment by lkeegan** [comment]
@rikardn I've added some documentation to the PR: https://github.com/lkeegan/symengine/blob/update_clang_format_version/CONTRIBUTING.md#code-formatting

**Comment by rikardn** [comment]
Great! The doc is useful. I'll approve this. One worry is that other PRs will need rebasing after this has been merged since it touches so many files. I guess it is unavoidable though.

**Review by rikardn — APPROVED** [review]

**Comment by isuruf** [comment]
Looks good to me. Give me a couple of days to update `isuruf-bot`

**Comment by isuruf** [comment]
I've taken down `isuruf-bot` for now. I'll re-enable it once I get some time.

**Review by isuruf — APPROVED** [review]

**Comment by lkeegan** [comment]
> Great! The doc is useful. I'll approve this. One worry is that other PRs will need rebasing after this has been merged since it touches so many files. I guess it is unavoidable though.

@rikardn Yes sorry about that - I'd be happy to do this for your existing PRs if that would help. (A semi-automatic way would be to first do an interactive rebase and edit each commit to have the new formatting `git diff HEAD~1 --name-only | xargs clang-format-11 -i`, then rebase on master)

**Pull request merged**
