### PR TITLE
[WIP] Polynomial wrappers

### PR DESCRIPTION
**Pull request by shivamvats**
Completes #511 

cc @certik @Sumith1896 

ToDo:

- [ ] Add encode and decode functions for `unordered_set`
- [ ] Add mul_poly

### CODE REVIEW

**Comment by certik** [comment]
Thanks for working on this. First we need it to compile, see the Travis tests.

**Comment by shivamvats** [comment]
Yes,  `encode` and ``decode` functions are missing as of now.

**Comment by shivamvats** [comment]
@certik Travis(and other checks) do not test with piranha. How do I add a `WITH_PIRANHA` test?

**Comment by certik** [comment]
@shivamvats I thought #585 does that.

**Comment by shivamvats** [comment]
@certik Yes, he opened it after my comment.

**Comment by certik** [comment]
We should make sure that at least one Travis test is testing this new code before merging.

Then we can figure out how to making it work using MSVC (and if Piranha doesn't work with it, which I think it doesn't, we can provide our own, perhaps slower, implementation of the classes that we use from Piranha).

**Comment by shivamvats** [comment]
@Sumith1896  There are test failures.

**Comment by shivamvats** [comment]
Closing in favour of #658

**Pull request closed without merging**
