### PR TITLE
[WIP] Improve setup.py

### PR DESCRIPTION
**Pull request by isuruf**
Already Done:
- Support Windows
- Give the user an option to specify Build Type and Generator
- Call `install` from `setup.py`

TODO

- [x] Compile `.py` to `.pyc`
- [x] Test in Windows
- [ ] Document how to use setup.py

Unrelated : Change `<prefix>/lib` to `<prefix>/libs` in Windows

### CODE REVIEW

**Comment by isuruf** [comment]
Some of the things that are new

- Using a different compiler for Windows
```
python setup.py build --compiler=mingw --define="GMP_DIR=C:\MinGW"
python setup.py install
```

- Installing the library to user directory (`~/.local`) would install `libsymengine` to `~/.local/lib` and python wrappers to `.local/lib/pythonX.Y/site-packages`

```
python setup.py install --user
```

**Comment by certik** [comment]
I wonder if we shouldn't rather split the Python wrappers off the main symengine repository, and then just use distutils or setuptools to build the Cython wrappers, and link against already built symengine library, that must be present on the system.

**Comment by isuruf** [comment]
Yes, removing `cmake` from the python wrappers is a good thing, but when it comes to finding libraries and headers for the python wrappers, is a build system on it own. For example, https://github.com/matplotlib/matplotlib/blob/master/setupext.py. 

Btw, moving the `setup.py` file from root and relocating it to `symengine/python` folder and distributing it works. So, we can easily split the two projects.

**Comment by certik** [comment]
I definitely don't want to maintain what Matplotlib does, that's not the way to go (and in fact it is also very often broken). We can keep using cmake to install the Python wrappers, and just call it from setup.py, it's actually not a bad solution.

**Comment by bjodah** [comment]
If you split the symengine python wrappers into their own package I would recommend to distribute the cythonized .cpp file (that is actually what the cython-devs recommend, and it's [quite simple](https://github.com/bjodah/pycvodes/blob/master/setup.py#L23)) and just use distutils to compile that single cpp file and link it with libsymengine. That removes two build-dependencies: cython & cmake.

I would actually recommend distributing pre-cythonized sources no matter what since that removes Cython as a build-dependency for end users.

The downside of separating the wrappers, as I see it, is that the C++ sources and the Python wrappers will be out of sync at times, which means that the Python wrappers need to track tagged releases of symengine. That is not too bad if releasing minor revisions of symengine is a quick and painless (or is the C++ core already considered mature?).

**Comment by isuruf** [comment]
Yes, removing cython as a dependency is an easy task.
How do you recommend handling dependencies? We need to link with `libsymengine` and its dependencies as well (if `libsymengine` is a static library) Also we need to know the directories of the dependencies, so that they can be included with `-I` flags. These include hard dependencies like `libgmp` and `libgmpxx`, and optional dependencies like `libarb` and `libmpfr`

**Comment by bjodah** [comment]
My comment was mainly about Cython as a build dependency. I'm afraid I don't have enough experience to give any guidance on the C++ distribution/dependency handling part. I guess that if `libsymengine` is a dynamic library it's left to the end user to set `LIBRARY_PATH` and `INCLUDE_PATH` appropriately at build-time (and LD_LIBRARY_PATH at run-time).

Now speculating: would it be possible to have cmake generate a tiny python lib upon configuration of libsymengine (lets call the tiny python library "libsymengine" as well) and then have `setup.py` in the python wrappers call `libsymenginge.get_include()` and `libsymenginge.get_libs()` or something along those lines to set the `-I` and `-l` flags appropriately? Overall I'm not at all convinced that splitting up the repo into library and wrappers would make it dependency handling any easier.

**Comment by certik** [comment]
@bjodah that is certainly possible, but I think it's much simpler to just use cmake to install the Python wrappers, and the setup.py is just a tiny wrapper on top. If anything goes wrong, it happens in cmake and we can easily debug it, because we have to have the cmake working anyway.

You are right that if we split it (or even if not), we can include the generated cpp file in our tarball releases. But as @isuruf said, the problem is with linking to libraries and including include files of all our dependencies that are exposed via the public header files.

Now in C++, there is actually a way to hide the fact that we depend on let's say Piranha, simply by only including it in the .cpp files that are already compiled in the symengine library. Then users don't have to care. Except that you still need to link against it, unless you use a dynamic library and rpath, but that's not always possible (e.g. in Debian).

So for all these reasons, I think the safest is to simply to specify to cmake all locations of our depenencies (include files, and all the .so, .a, .dylib, .dll, ... libraries, as well as which order to link them), and then once cmake knows, it will do the right thing. 
CMake allows to save this configuration into a generated .cmake file and when building a user project, one simply loads this .cmake file in it. So if e.g. the Python wrappers split, they can still use cmake underneath and this cmake would load the configuration file. And then things will truly just work. Binary installations of symengine (e.g. in Debian) would also have to distribute this .cmake file.

**Comment by bjodah** [comment]
@certik I see, I learned something new. Thank you.
Actually, familiarizing myself with `symengine_wrapper.pyx` I see we have tons of [conditional statements](http://docs.cython.org/src/userguide/language_basics.html#conditional-statements). So I guess removing Cython as a build dependency would actually be quite hard.

**Comment by Sumith1896** [comment]
Is this up in `symengine.py`?

**Comment by isuruf** [comment]
Not yet. I'm still working on it. I will send a PR tomorrow.

**Comment by isuruf** [comment]
Fixed in symengine/symengine.py#8

**Pull request closed without merging**
