### PR TITLE
Simplify LibFindMacros.cmake

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by certik** [comment]
It seems to be working except the `cmake --find-package` thing. I tried to fix it in 28f729f27b77ccb4e81037e745e2dcc397470014, but it doesn't help, so it will need some more debugging.

**Comment by isuruf** [comment]
@certik, `cmake --find-package` does not use any of the compiler or linker dependent paths because the ompiler is not used at that stage. It is intended as a replacement to `pkg_config`.  Previously, GMP_DIR was taken into account so there was no need to look else where. What do you think about adding hints to `CMAKE_PREFIX_PATH` before each `find_package` call in `SymEngineConfig.cmake`?

**Comment by certik** [comment]
@isuruf so `CMAKE_PREFIX_PATH` is used for regular cmake run, but not for `cmake --find-package`? Or is `CMAKE_PREFIX_PATH` never used for `find_package`, no matter how cmake is invoked? It looks like something cmake should fix in itself.

**Comment by certik** [comment]
I've implemented absolute paths for now in `SymEngineConfig.cmake` for now. As @isuruf and I discussed on gitter, the relative paths are a bit tricky and we don't know yet the best way forward. So right now let's get the absolute paths working well first. Once we have that, then we can think about relative paths.

**Comment by certik** [comment]
I think it's working. @isuruf let me know what you think.

**Comment by isuruf** [comment]
Looks good. Need to update `README.md`

**Comment by certik** [comment]
Good point. Also, I'll send a PR to our Python wrappers and use this branch for symengine to make sure it actually works as expected. Only then I'll merge this PR.

**Comment by certik** [comment]
I tested this PR in https://github.com/symengine/symengine.py/pull/35 and it seems to be working just fine. (There are some unrelated failures there.)

**Comment by certik** [comment]
I updated README. This is ready to go in if tests pass.

**Comment by certik** [comment]
I restarted the AppVeyor build. If it passes, then I'll merge this.

**Pull request merged**
