### PR TITLE
Added -fsanitize Flags

### PR DESCRIPTION
**Pull request by ShikharJ**
relevant : #503

### CODE REVIEW

**Comment by srajangarg** [comment]
Why is this change required?

**Comment by ShikharJ** [comment]
This is just a test. I wanted to add Memory and Address Sanitizers to travis checks.

**Comment by srajangarg** [comment]
You should try and test stuff on your own repository (and travis). You can report whatever you wish to find, through that too.

**Comment by srajangarg** [comment]
Oh, and also link to the issue number and add relevant comments to the PR wherever possible.

**Comment by ShikharJ** [comment]
Ok. I'll keep that in mind. Thanks!

**Comment by certik** [comment]
I would like to enable these on Travis, but it has to be done on the clang builds only.

**Comment by ShikharJ** [comment]
@certik I'm on it.

**Comment by certik** [comment]
For now add the Address Sanitizer on the one linux clang build, and the Memory Sanitizer on the other one. We'll have to think how to best incorporate it. Perhaps we can convert some of the gcc builds to clang builds.

The failure seems to be:
```
 /usr/bin/ld: CMakeFiles/test_cwrapper.dir/test_cwrapper.c.o: relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

CMakeFiles/test_cwrapper.dir/test_cwrapper.c.o: could not read symbols: Bad value
```
I think we just need to add the `-fPIC` flag to the C build.

**Comment by certik** [comment]
See also #616.

**Comment by certik** [comment]
See also #1112 for test consolidation. We can free some slots that way, and add more clang tests, for example.

**Comment by isuruf** [comment]
@ShikharJ, I have a branch for this at, https://github.com/isuruf/symengine/tree/leak . Maybe you can finish it ?

**Comment by ShikharJ** [comment]
@isuruf That's just a guess for a failure. I might even be wrong. Anyways, if I do find a leak, I'll definitely try to fix that.

**Comment by ShikharJ** [comment]
@certik  I have consolidated some of the builds on travis, and added some more clang builds locally (with memory and address sanitizers as MSAN and ASAN respectively). However, I am still unable to resolve the recompilation (of C builds in test cases 13 and 14) using -fPIC. Also, the address sanitizer is throwing up issues of its own (test cases 15 and 16). Please take a look.
https://travis-ci.org/ShikharJ/symengine/builds/173169479

**Comment by certik** [comment]
Did you set the -fPIC for the C compiler? Because this PR seems to only have it for the C++ compiler.

**Comment by ShikharJ** [comment]
I'll try that and get back to you. Also, any suggestions for test cases 15 and 16?

**Comment by certik** [comment]
Not sure. Maybe the clang version is a bit broken on Travis.

**Comment by isuruf** [comment]
@ShikharJ, can you send a PR with the new changes with a WIP tag in the title?

**Comment by ShikharJ** [comment]
@isuruf Sure.
Also, I browsed through some links online. Please refer to them also, as I think they might be related to this problem.
http://stackoverflow.com/questions/37970758/how-to-use-addresssanitizer-in-gcc
https://github.com/google/sanitizers/issues/380

**Pull request closed without merging**
