### PR TITLE
Four fixes

### PR DESCRIPTION
**Pull request by srajangarg**
see commit messages

### CODE REVIEW

**Comment by certik** [comment]
It looks like there is a genuine failure on Windows (https://ci.appveyor.com/project/certik/symengine/build/1954/job/y0epb221mh6l32gy), though I don't understand why it doesn't happen on linux as well.

**Comment by srajangarg** [comment]
You mean it's a problem on master too right? Can an appveyor build be started on master again?

**Comment by certik** [comment]
That's a good question if it happens in master too, we need to investigate it. Here is the list of the latest builds: https://ci.appveyor.com/project/certik/symengine/history

**Comment by srajangarg** [comment]
All builds pass on master https://github.com/symengine/symengine/pull/1034

I tried logging into the VM, and tried debugging but failed. I am not able to figure out what's going wrong. What's more surprising is that it fails on a `coeff` test, which has no relation to the changes in this PR.

The assertion failing is `test_basic : 826`  
```
y = symbol("y");
z = symbol("z");
r1 = add(x, pow(y, integer(2)));
REQUIRE(eq(*coeff(*r1, *x, *integer(1)), *integer(1)));
```
It returns `2` instead of `1`.

**Comment by certik** [comment]
@srajangarg  try to submit another (fake) commit here and see if it passes. Perhaps it's just a fluke. That would suggest that your code doesn't trigger it. Otherwise, perhaps your code does trigger it, somehow. Let's figure it out.

**Comment by srajangarg** [comment]
Okay, after patiently debugging thorugh the VM (lag + Windows = hell) I think I figured it out.

It's a problem with the `CoeffVisitor` defined in `visitor.h`. Look at the `Pow` visit,
```
void bvisit(const Pow &x)
{
    if (eq(*x.get_base(), *x_) and eq(*x.get_exp(), *n_)) {
        coeff_ = one;
    }
}
```
It doesn't set the `coeff_` to zero, if the base/exp doesn't match. An example to illustrate, consider `x+ y**2`. We goto the `Add` visit and start iterating over the elements. Here's the `Add` visit:
```
void bvisit(const Add &x)
{
    umap_basic_num dict;
    RCP<const Number> coef = zero;
    for (auto &p : x.dict_) {
        p.first->accept(*this);
        if (neq(*coeff_, *zero)) {
            Add::coef_dict_add_term(outArg(coef), dict, p.second, coeff_);
        }
    }
    coeff_ = Add::from_dict(coef, std::move(dict));
}
```
Say we get `x` first, we see that by the end of the loop, `coeff_ = 1` and `coef = 1`, no other changes. Now we get `y**2`, when we do `y**2 -> accept(*this)` because it doesn't match (as needed in the Pow bvisit) nothing happens, no changes. But! `coeff_` still is `1`, and hence `coef` gets updated to `2` via `coeff_dict_add_term` (Ideally, we didn't want it to be called)

And finally `coeff_` becomes `2` after constructing from `coef` and the empty `dict`.

The fix : Probably just 
```
void bvisit(const Pow &x)
{
    if (eq(*x.get_base(), *x_) and eq(*x.get_exp(), *n_)) {
        coeff_ = one;
    } else {
        coeff_ = zero;
    }
}
```

Why is it not affecting other PRs/Travis builds?
The current code works if the order in which we iterated was the other way round ie `y**2` first and then `x`. Wild guess is that, due to the changed in the order of values in `typecodes.inc` in this PR the MSVC compiler is the only one to change the order of the elements while iterating over the `Add`? I'm not sure about this.

**Comment by srajangarg** [comment]
It passeth! :smile:

**Comment by isuruf** [comment]
Nice. Great work.

**Comment by certik** [comment]
Thanks @srajangarg for figuring out where the bug was! Much appreciated.

**Comment by srajangarg** [comment]
@isuruf @certik did the allow failure move. Please merge.

**Comment by certik** [comment]
Can you write a test for the fix you introduced in 62c824d793b8f20268a5a003ddd595286c7981d1? Otherwise it looks good.

**Comment by certik** [comment]
@srajangarg thanks. I tested 3303b25eb667060c2b3bb0fe39affa8a5144ebca cherry picked on top of the master and it fails, and then I tested your PR and everything works. 

+1 to merge as it is, if tests pass.

**Comment by certik** [comment]
@srajangarg I just gave you push access. Feel free to merge PRs (including this one), but please make sure they are reviewed and that all tests pass.

**Comment by srajangarg** [comment]
Thanks a lot @certik ! If it's possible, can I get access to stop/restart builds on Travis and Appveyor? Lots of times need it for testing and cancelling builds which have been pushed by mistake etc.

**Comment by certik** [comment]
Check Travis, you should have access to it as well, you might need to log in and out --- I thought Travis does it by github access. If not, let me know, I would need to look into it.

**Pull request merged**
