### PR TITLE
Allow implicit multiplication for variables in parser

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by srajangarg** [comment]
Is this a standard feature for parsers?

**Comment by isuruf** [comment]
Some parsers of programming languages allow this. For eg: Julia accepts all the new test cases I've added here.

**Comment by srajangarg** [comment]
Understanding these changes is very difficult, because of the hacky code.

**Comment by isuruf** [comment]
Thanks for the review

**Comment by vlovero** [comment]
Is there a simple modification to allow implicit multiplication between two variables?
For example `1 - x y` would be parsed as `1 - x * y`.

**Comment by isuruf** [comment]
Not really. We'll have to change the grammar based on a flag, because `f(x)` can be interpreted as `mul(f, x)` or `call(f, x)`.
Can you open an issue?

**Pull request merged**
