### PR TITLE
Trigonometric table tests

### PR DESCRIPTION
**Pull request by nishnik**

### CODE REVIEW

**Comment by nishnik** [comment]
Look at Travis output:
```
Running make:

+make

Scanning dependencies of target teuchos

[  1%] Building CXX object symengine/utilities/teuchos/CMakeFiles/teuchos.dir/Teuchos_dyn_cast.cpp.o

[  2%] Building CXX object symengine/utilities/teuchos/CMakeFiles/teuchos.dir/Teuchos_Ptr.cpp.o

[  3%] Building CXX object symengine/utilities/teuchos/CMakeFiles/teuchos.dir/Teuchos_RCPNode.cpp.o

[  5%] Building CXX object symengine/utilities/teuchos/CMakeFiles/teuchos.dir/Teuchos_TestForException.cpp.o

[  6%] Building CXX object symengine/utilities/teuchos/CMakeFiles/teuchos.dir/Teuchos_TypeNameTraits.cpp.o

[  7%] Building CXX object symengine/utilities/teuchos/CMakeFiles/teuchos.dir/Teuchos_stacktrace.cpp.o

Linking CXX static library libteuchos.a

[  7%] Built target teuchos

Scanning dependencies of target symengine

[  8%] Building CXX object symengine/CMakeFiles/symengine.dir/symengine_rcp.cpp.o

[ 10%] Building CXX object symengine/CMakeFiles/symengine.dir/basic.cpp.o

[ 11%] Building CXX object symengine/CMakeFiles/symengine.dir/dict.cpp.o

[ 12%] Building CXX object symengine/CMakeFiles/symengine.dir/symbol.cpp.o

[ 14%] Building CXX object symengine/CMakeFiles/symengine.dir/number.cpp.o

[ 15%] Building CXX object symengine/CMakeFiles/symengine.dir/integer.cpp.o

[ 16%] Building CXX object symengine/CMakeFiles/symengine.dir/rational.cpp.o

[ 17%] Building CXX object symengine/CMakeFiles/symengine.dir/complex.cpp.o

[ 19%] Building CXX object symengine/CMakeFiles/symengine.dir/constants.cpp.o

[ 20%] Building CXX object symengine/CMakeFiles/symengine.dir/add.cpp.o

[ 21%] Building CXX object symengine/CMakeFiles/symengine.dir/mul.cpp.o

[ 23%] Building CXX object symengine/CMakeFiles/symengine.dir/pow.cpp.o

[ 24%] Building CXX object symengine/CMakeFiles/symengine.dir/functions.cpp.o

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```
I think it is not related to PR.

**Comment by certik** [comment]
I think that this looks good. Travis seems to be passing now?

@nishnik Thanks for writing the tests.

@thilinarmtb any objections?

**Comment by thilinarmtb** [comment]
Looks good to me. +1 for merging as it is.

**Comment by nishnik** [comment]
Ping @certik

**Comment by isuruf** [comment]
@nishnik, thanks for the PR

**Pull request merged**
