### PR TITLE
Namechanges : Polys

### PR DESCRIPTION
**Pull request by srajangarg**
For https://github.com/symengine/symengine/issues/959

### CODE REVIEW

**Comment by srajangarg** [comment]
@isuruf @Sumith1896

**Comment by isuruf** [comment]
How about,
`UIntPolyO` -> `UIntPoly`
`UExprPolyO` -> `UExprPoly`
`UExprODict` -> `UExprDict`
`UIntODict` -> `UIntDict` ?

`O` is really unnecessary.

**Comment by isuruf** [comment]
Also how about changing,
`symengine/uintpoly.h` -> `symengine/polys/uint.h`
This would introduce a folder inside `symengine`, but I think it is good to avoid lots of files in the main folder.

@certik, what do you think?

**Comment by srajangarg** [comment]
the `O` is for `ordered`. We might implement unordered containers in the future right? I think we should name these considering this. Not necessarily `UIntPolyO`, but something else perhaps?

**Comment by isuruf** [comment]
If they are implemented in the future, we can name the new containers with appropriate names and typedef `UIntPoly` to something more appropriate. I think we won't have other implementations in the near future. (Unordered containers should only be implemented if the ordered containers are not enough for a specific use case that a user may request. Not synthetic benchmarks)

**Comment by srajangarg** [comment]
Okay then

**Comment by isuruf** [comment]
@chenchfort, @irislq, any comments?

**Comment by irislq** [comment]
I agree with leaving out the `O` in the name like Isuru suggested (I thought this was a zero at first and I got really confused). Otherwise it looks good and I don't have any other complaints.

**Comment by certik** [comment]
I agree with @isuruf:

UIntPolyO -> UIntPoly
UExprPolyO -> UExprPoly
UExprODict -> UExprDict
UIntODict -> UIntDict

**Comment by isuruf** [comment]
@certik, what do you think about a folder polys inside?

**Comment by srajangarg** [comment]
@isuruf ping

**Comment by Sumith1896** [comment]
I'm +1 for a folder. We eventual will need to have that.

**Pull request merged**
