### PR TITLE
add evaluate class for nan

### PR DESCRIPTION
**Pull request by ranjithkumar007**
like for log(Nan) ..master throws an error message of Not Implemented.
Instead returning Nan is a better way.
TO-DO - 
~~- [ ] for functions not in evaluate class check if arg is Nan and return Nan there itself.~~
- [x] Add tests

@isuruf  please review and suggest changes.

### CODE REVIEW

**Comment by ranjithkumar007** [comment]
@isuruf  for functions like pow() i thought we might add a check for arg as Nan or not ? I didn't get why you striked that first TODO out ..is there any other way around ?

**Comment by isuruf** [comment]
There is little use of NaN except to signal that your computation is wrong. There is no need to special case for NaN and slow down other functions.

**Comment by ranjithkumar007** [comment]
thanks for the clarification !!

**Comment by isuruf** [comment]
This PR contains the erroneous commit, 855a295. You should remove it

**Comment by ranjithkumar007** [comment]
thanks for the merge!

**Pull request merged**
