### PR TITLE
rename PZERO -> pzero

### LINKED ISSUE #1083: Problem building with Piranha
I'm putting together a package for the [Spack package manager](https://github.com/LLNL/spack), and have hit a problem when building with the Piranha CAS library. I'm not quite sure whether this is a symengine problem or a piranha problem. I've attached the [build log](https://github.com/symengine/symengine/files/504445/spack-build.txt) for your perusal, with the salient lines being
```
/private/var/folders/lc/b4bjrtcn69d279m6rf4f42y00000gn/T/jp/spack-stage/spack-stage-3YZfHb/symengine/symengine/polys/uintpoly_piranha.h:217:19: error: expected unqualified-id
        static Cf PZERO(0);
                  ^
/usr/include/sys/param.h:124:15: note: expanded from macro 'PZERO'
#define PZERO   22              /* No longer magic, shouldn't be here.  XXX */
```

### LINKED ISSUE #1085: Problem building with Piranha (2)
A follow up issue after #1083 is fixed with #1084 . [Build log](https://github.com/symengine/symengine/files/504503/spack-build.txt) attached.

I should mention that this is built against the development version of `Piranha` on `OSX 10.11 El Capitan`.

```
/private/var/folders/lc/b4bjrtcn69d279m6rf4f42y00000gn/T/jp/spack-stage/spack-stage-QwVtWj/symengine/symengine/polys/uintpoly_piranha.h:115:25: error: 'container_type' is a protected member of 'piranha::series<piranha::mp_integer<0>, piranha::monomial<unsigned int, std::__1::integral_constant<unsigned long, 0> >, piranha::polynomial<piranha::mp_integer<0>, piranha::monomial<unsigned int, std::__1::integral_constant<unsigned long, 0> > > >'
    typename Container::container_type::const_iterator ptr_;
```

### PR DESCRIPTION
**Pull request by isuruf**
PZERO is a macro in some system headers and conflicts with symengine's definition

Fixes #1083
Fixes #1085

@jppelteret, can you confirm that this fixes the problem for you?
Btw, what is the OS you are building symengine on?

### CODE REVIEW

**Comment by jppelteret** [comment]
Great, thanks a lot for the quick response! This seems to fix the problem, but another one has cropped up in its place :-( I'll open up a new issue for it though.

I'm building on `OSX 10.11 El Capitan`.

**Comment by certik** [comment]
The OSX builds failed with:
```
Error: cmake-3.0.2 already installed
To install this version, first `brew unlink cmake`
```
What is the minimal cmake version that we require? Is 3.0.2 enough?

**Comment by certik** [comment]
Otherwise +1.

**Comment by certik** [comment]
We can probably just merge this PR, and fix the OS X test problem in another PR, as it is unrelated.

**Comment by certik** [comment]
+1 if tests pass.

**Comment by isuruf** [comment]
Thanks everyone for the input.

**Pull request merged**
