### PR TITLE
Improve coverage of some sources

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
Besides the two simple questions, this looks good.

**Comment by certik** [comment]
Btw, there is lots of dead code starting here: https://coveralls.io/builds/5306822/source?filename=symengine%2Fmul.cpp#L109, so we should think carefully if there is a way to trigger it. If not, then we can add a Debug time check in there, but remove the if statements whose bodies are never executed. That should speed up the code, since no if check needs to be done in Release mode.

**Comment by isuruf** [comment]
Yes, I'll check if there's a way to trigger it.

**Comment by isuruf** [comment]
This is now ready for review

**Comment by rwst** [comment]
I think it's fine.

**Pull request merged**
