### PR TITLE
remove binary

### PR DESCRIPTION
**Pull request by rwst**

### CODE REVIEW

**Comment by Sumith1896** [comment]
@rwst Have you done `filter-branch` of this binary? 
Usually even if you remove the binary, it stays in the history. I and @isuruf had encountered this before.

**Comment by rwst** [comment]
No I have not.

**Comment by rwst** [comment]
@isuruf Maybe you should better do this on master.

**Comment by Sumith1896** [comment]
Agreed.

**Comment by isuruf** [comment]
@certik, what do you think?. This was already merged at #668. Should I change the history or merge this branch?

**Comment by rwst** [comment]
The branch is already deleted.

**Comment by certik** [comment]
Oh, I'll try to fix this today. Which PR got it in? Is everybody ok with
removing it from history as well? Hashes will change.

**Comment by certik** [comment]
Isuru, can you prepare a branch that's master with this binary removed?
Let's review it and then we can force push it to master. My apologies for
missing it!

**Comment by Sumith1896** [comment]
@certik I have such a branch up on my github. Shall I send in a PR?
cc @isuruf @rwst

**Comment by isuruf** [comment]
@Sumith1896, this one, https://github.com/Sumith1896/csympy/tree/binary, right? I looked over it and it looks good. Thanks

**Comment by certik** [comment]
I'll check in in about an hour or so and let you know.

**Comment by certik** [comment]
The binary file is here: https://github.com/symengine/symengine/pull/668/files#diff-5a609ef561f5bb181dd342bcecd9aadf, I totally missed it.

**Comment by certik** [comment]
I just forced pushed @Sumith1896's branch into master. I had to temporarily disable the master branch protection, otherwise github refuses to force push.

**Comment by certik** [comment]
The Travis tests for this new master are run here: https://travis-ci.org/symengine/symengine/builds/97263717

**Pull request closed without merging**
