### PR TITLE
series_flint: use Flint C API instead of C++ API

### PR DESCRIPTION
**Pull request by rwst**
First half of move to Flint C API.

### CODE REVIEW

**Comment by srajangarg** [comment]
There's still `flint::fmpzxx` used in places like `polys/uintpoly_flint.*`. Do those need change? I wrote them recently.

**Comment by isuruf** [comment]
@srajangarg, yes, they need to be changed.

**Comment by rwst** [comment]
That's why I wrote "first half". I want this merged first.

**Comment by Sumith1896** [comment]
@rwst Travis complains `flint_wrapper.h is not installed!`. That should be fixable, could you please do that?

**Comment by rwst** [comment]
I should have looked earlier, thanks!

**Comment by isuruf** [comment]
Thanks for the PR

**Comment by Sumith1896** [comment]
Thanks @rwst

**Pull request merged**
