### PR TITLE
Moved catch and teuchos dir to utilities dir

### PR DESCRIPTION
**Pull request by CodeMaxx**
Moved the `catch` and `teuchos` dir to `symengine/utilities` dir and changed the  `cmake` files accordingly so as it compiles properly.
But since I used an in-source compile the build files are also a part of the this commit . 
How are these to be removed?

### CODE REVIEW

**Comment by CodeMaxx** [comment]
fix for #711

**Comment by certik** [comment]
You committed too many files in this commit. You should only commit files that you changed.

**Comment by CodeMaxx** [comment]
Yes I know . The build files have been committed as well. Is there a way to delete the files created by running `cmake .` and then `make` from my local directory? Otherwise I'll manually search for the files and push a commit.

**Comment by CodeMaxx** [comment]
What about the moved files?

**Comment by Sumith1896** [comment]
do a `git clean -dfx`

**Pull request closed without merging**
