### PR TITLE
implement skip-stop traversal, example has_function_of_symbol

### PR DESCRIPTION
**Pull request by rwst**

### CODE REVIEW

**Comment by rwst** [comment]
Ultimately I did not need this, but you may be interested nevertheless.

**Comment by certik** [comment]
We should add some tests showing how to use this.

**Comment by Sumith1896** [comment]
@rwst There some changes in the master, `visitor.h` I think. This needs to be updated. Also, tests too.

**Comment by certik** [comment]
I am going to close this for now. @rwst if you want this in, we can always finish it, add tests, etc. later.

**Pull request closed without merging**
