### PR TITLE
Fix deprecated function declarations

### PR DESCRIPTION
**Pull request by thilinarmtb**

### CODE REVIEW

**Comment by certik** [comment]
@thilinarmtb what warning does this show? I thought the `void` argument is the deprecated way.

**Comment by thilinarmtb** [comment]
@certik : Thanks for approving the changes. I got the following when I included `symengine`
in a project I compile with `-Wall -Wextra -Wpedantic`. I can reproduce it with the following
simple file:
```bash
thili@M2-Pro Misc % cat deprecated.c 
void foo() {}

int main(int argc, char **argv) {
  foo();
  return 0;
}
thili@M2-Pro Misc % gcc deprecated.c -Wall -Wextra -Wpedantic
deprecated.c:1:9: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
void foo() {}
        ^
         void
deprecated.c:3:14: warning: unused parameter 'argc' [-Wunused-parameter]
int main(int argc, char **argv) {
             ^
deprecated.c:3:27: warning: unused parameter 'argv' [-Wunused-parameter]
int main(int argc, char **argv) {
                          ^
3 warnings generated.
```

**Comment by thilinarmtb** [comment]
In C, I think use of `foo(void)` in the parameter list implies empty parameter list
whereas `foo()` declares a function that takes an unspecified number of fixed
parameters.

**Comment by certik** [comment]
Thanks! I see, this only happens in the C wrappers. Thanks for the fix.

**Pull request merged**
