### PR TITLE
Adding C wrappers

### PR DESCRIPTION
**Pull request by kunal-iitkgp**
I'm adding c wrappers for sec(),cot() and cosec(). 
I will be adding tests for the same  into   `symengine/tests/cwrapper/test_cwrapper.c`  soon.

### CODE REVIEW

**Comment by certik** [comment]
That looks good. We should wrap all trigonometric functions.

**Comment by rajithv** [comment]
Hi @kunal-iitkgp , The trigonometric functions are wrapped in #822 . In fact I have wrapped all the one argument functions.

**Comment by abinashmeher999** [comment]
Hi @kunal-iitkgp. You might want to try wrapping up some functions in `ntheory`.

**Comment by kunal-iitkgp** [comment]
@abinashmeher999 sure .Thanks!!

**Comment by isuruf** [comment]
Closed because of #822

**Pull request closed without merging**
