### PR TITLE
Add support for log in LLVMDoubleVisitor

### PR DESCRIPTION
**Pull request by ShikharJ**
Relevant: #1213 

TODO:
- [x] `log`
- [ ] `tan`
- [ ] `abs`
- [ ] `Basic`

### CODE REVIEW

**Comment by isuruf** [comment]
Looks good to me. Can you add tests?

**Comment by ShikharJ** [comment]
@isuruf How should I implement functions that are not recognised under `llvm::Intrinsic` namespace (such as tan or abs)? I tried to search online but couldn't find a good resource.

**Comment by isuruf** [comment]
@ShikharJ, see here, https://github.com/symengine/symengine/issues/1213#issue-208721222

**Comment by isuruf** [comment]
@ShikharJ, ping

**Comment by isuruf** [comment]
I'm going to merge this as it adds support for log. We can add the other functions in another PR.

**Pull request merged**
