### PR TITLE
Few optimizations

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
How do benchmarks change?

**Comment by isuruf** [comment]
`./expand6 1000` changed from 6834ms to 5667ms.

**Comment by certik** [comment]
And the others?

**Comment by isuruf** [comment]
I checked `add1`, `expand1` and `expand2`. They don't seem to be affected.

**Comment by certik** [comment]
Perfect. The changes look good. Merging.

**Pull request merged**
