### PR TITLE
Base change

### PR DESCRIPTION
**Pull request by nishnik**
Changes base class from `UPolyBase` to `UIntPolyBase`, `pow` added and `eval` functions.

### CODE REVIEW

**Comment by srajangarg** [comment]
You might have to wait for URatpoly to get merged in first, because it introduces a lot of changes to the polynomial structure.

**Comment by srajangarg** [comment]
+1

**Comment by isuruf** [comment]
I'm not sure whether this is needed. `UIntPolyBase` has `as_symbolic`, but for GaloisField it doesn't make sense. What do you think?

**Comment by isuruf** [comment]
We can throw in that case

**Pull request merged**
