### PR TITLE
Add Pieter and Zgoda to SymEngine AUTHORS file

### PR DESCRIPTION
**Pull request by isuruf**
@PerformanceCoder @eendebakpt @HaoZeke let me know if your name and email address are correct.

### CODE REVIEW

**Review by rikardn — APPROVED** [review]
Welcome!

**Comment by HaoZeke** [comment]
Yup, looks great, thanks @isuruf

**Comment by eendebakpt** [comment]
Looks good to me

**Comment by isuruf** [comment]
I'm going to merge this. @PerformanceCoder, let me know if you want to change your name/email. I'll send a separate PR if needed.

**Comment by PerformanceCoder** [comment]
Hi!

@isuruf, thank you for adding me to the autors list! Unfortunately, current email is no longer valid, the actual one is 20000703@edu.spbgasu.ru

**Pull request merged**
