### PR TITLE
fix 'latest' llvm CI job: add apt packages and use ubuntu 24.04

### PR DESCRIPTION
**Pull request by lkeegan**

### CODE REVIEW

**Comment by MinnieMouse11** [comment]
Hi @rikardn, Can you have a look?

**Comment by rikardn** [comment]
LGTM. Why doesn't all tests run?

**Comment by lkeegan** [comment]
> LGTM. Why doesn't all tests run?

I think this is because "required" tests is just a list of test names, but the test name includes all of the build options, so when the CI is updated the names change, but the list of required tests is not updated and now has names that are no longer present in the CI.

I think the solution would be to add a fixed name for each job, then update the list of required jobs (which can only be changed by an admin.)

**Comment by EinavS1** [comment]
@lkeegan it looks like there are still pending checks that do not start

**Comment by MinnieMouse11** [comment]
@lkeegan it looks like there are still pending checks that do not start

**Comment by oliverlee** [comment]
> > LGTM. Why doesn't all tests run?
> 
> I think this is because "required" tests is just a list of test names, but the test name includes all of the build options, so when the CI is updated the names change, but the list of required tests is not updated and now has names that are no longer present in the CI.
> 
> I think the solution would be to add a fixed name for each job, then update the list of required jobs (which can only be changed by an admin.)

You could also use this workflow if you want to define a single stable job name:
https://github.com/re-actors/alls-green

**Comment by lkeegan** [comment]
@oliverlee thanks for the suggestion, looks promising!

**Comment by lkeegan** [comment]
closing in favour of #2049

**Pull request closed without merging**
