### PR TITLE
Don't revisit in diff

### PR DESCRIPTION
**Pull request by isuruf**
This reverts commit 297a403fd51b1d366cdedde348799a7a69271bda.

### CODE REVIEW

**Comment by certik** [comment]
This PR seems to significantly speedup the S3 and S3a benchmarks. Master:
```
$ ./benchmarks/symbench 
Time for R1 : 	     0.000568959
Time for R2 : 	     0.008805386
Time for R3 : 	     0.000001955
Time for R5 : 	     0.000026471
Time for R7 : 	     0.037667314
Time for R8 : 	     0.013665216
Time for S1 : 	     0.014141421
Time for S2 : 	     0.017655613
Time for S3 : 	     0.011891636
Time for S3a : 	     1.144806982
```
and this PR:
```
$ ./benchmarks/symbench Time for R1 : 	     0.001033989
Time for R2 : 	     0.011560081
Time for R3 : 	     0.000001536
Time for R5 : 	     0.000007124
Time for R7 : 	     0.028283121
Time for R8 : 	     0.010158847
Time for S1 : 	     0.009917810
Time for S2 : 	     0.013434098
Time for S3 : 	     0.004066179
Time for S3a : 	     0.763254177
```
I don't know if there could be other benchmarks for differentiating that could be slower with this PR.

**Comment by ichumuh** [comment]
Holy shit guys, i tried my test mentioned in https://github.com/symengine/symengine.py/issues/293#issuecomment-518681981 and the runtime spend on jacobians went from `~45`s down to `0.66`s. Please merge, thanks.

**Comment by ichumuh** [comment]
It also seems like this fixes https://github.com/symengine/symengine.py/issues/293.

**Comment by certik** [comment]
@ichumuh thanks for testing it. Nice speedup!

**Comment by isuruf** [comment]
Note that for expressions without common subexpressions, this adds an overhead.
`x.diff(x) : 447 ns vs 112 ns`
`(x+y).diff(x): 1980 ns vs 1028 ns`
`sqrt(x**2+y**2).diff(x): 19125 ns vs 17435 ns`

**Comment by ichumuh** [comment]
I see, I have a LOT of common subexpressions. Would be interesting to see how this overhead scales for large expressions.

**Comment by certik** [comment]
> Note that for expressions without common subexpressions, this adds an overhead.
> `x.diff(x) : 447 ns vs 112 ns`
> `(x+y).diff(x): 1980 ns vs 1028 ns`
> `sqrt(x**2+y**2).diff(x): 19125 ns vs 17435 ns`

@isuruf can you please add benchmarks for these? Just create a new `diff` benchmark that benchmarks expressions both with and without common subexpressions.

So I think we should add a flag to `diff`, say, `cache=true/false`. If `cache=false`, then it will be very fast for expressions without common subexpressions. With `cache=true`, it will be fast for @ichumuh's use case. We can debate which one should be the default, perhaps even `cache=true`, as long as there is a way to turn it off to recover performance for expressions that don't benefit from this.

**Comment by ichumuh** [comment]
I had some time and wrote two benchmarks. I can't make a pull request to a pull request, but I can make a new one if you'd like
```
double CommonSubexprDiff()
{
    RCP<const Basic> e;
    RCP<const Basic> f;

    std::string tmp_str = "a";
    std::vector<RCP<const Basic>> v;
    for (int i=0; i<20; ++i) {
        v.push_back(symbol(tmp_str));
        tmp_str += "a";
    }

    e = integer(23);
    for (uint i=0; i < v.size(); ++i) {
        RCP<const Basic> z = symbol(tmp_str);
        e = pow(e, add(cos(sqrt(log(sin(pow(v[v.size()-i-1],v[i]))))), e));
    }
    e = expand(e);

    auto t1 = std::chrono::high_resolution_clock::now();
    f = e->diff(rcp_static_cast<const Symbol>(v[0]));
    auto t2 = std::chrono::high_resolution_clock::now();
    return std::chrono::duration<double>(t2 - t1).count();
}

double NoCommonSubexprDiff()
{
    RCP<const Basic> e;
    RCP<const Basic> f;

    std::string tmp_str = "a";
    std::vector<RCP<const Basic>> v;
    for (int i=0; i<5000; ++i) {
        v.push_back(symbol(tmp_str));
        tmp_str += "a";
    }

    e = integer(23);
    for (uint i=0; i < v.size(); ++i) {
        RCP<const Basic> z = symbol(tmp_str);
        e = pow(e, cos(sqrt(log(sin(pow(v[v.size()-i-1],v[i]))))));
    }
    e = expand(e);

    auto t1 = std::chrono::high_resolution_clock::now();
    f = e->diff(rcp_static_cast<const Symbol>(v[0]));
    auto t2 = std::chrono::high_resolution_clock::now();
    return std::chrono::duration<double>(t2 - t1).count();
}
```
Output for new version:
```
$ ./benchmarks/symbench
Time for R1 : 	     0.000386178
Time for R2 : 	     0.007895843
Time for R3 : 	     0.000000246
Time for R5 : 	     0.000011804
Time for R7 : 	     0.034454548
Time for R8 : 	     0.012680034
Time for S1 : 	     0.011085706
Time for S2 : 	     0.013978047
Time for S3 : 	     0.006486639
Time for S3a : 	     0.832221468
Time for CommonSubexprDiff : 	     0.456230436
Time for NoCommonSubexprDiff : 	     5.706496920
```
Output for old version:
```
$ ./benchmarks/symbench
Time for R1 : 	     0.000539666
Time for R2 : 	     0.009319156
Time for R3 : 	     0.000000238
Time for R5 : 	     0.000011912
Time for R7 : 	     0.034462731
Time for R8 : 	     0.012698138
Time for S1 : 	     0.011182440
Time for S2 : 	     0.013213944
Time for S3 : 	     0.011657048
Time for S3a : 	     1.308172022
Time for CommonSubexprDiff : 	    15.857334339
Time for NoCommonSubexprDiff : 	     3.956042846

```
With the old version the benchmark eats ~1gb of memory during `CommonSubexprDiff` and with the new version it eats ~2.2gb during `NoCommonSubexprDiff`.

**Comment by certik** [comment]
Thanks! I think we just make the cache enabling configurable, and that will allow us to obtain the better performance in each benchmark.

**Comment by isuruf** [comment]
@ichumuh, can you send a separate PR to this repo?

**Comment by isuruf** [comment]
Benchmark now prints,
```
Time for expr with common subexpressions (with cache) :              0.000500374
Time for expr with common subexpressions (without cache) :           0.052888885
Time for expr without common subexpressions (with cache) :           0.000742454
Time for expr without common subexpressions (without cache) :        0.000452124
```

**Comment by isuruf** [comment]
Ready for a review

**Comment by ichumuh** [comment]
Thanks. If I understand your changes correctly, then the parameter was only added to diff, not jacobians. Can you do that as well please?

**Comment by certik** [comment]
This looks good to me. Thanks!

**Comment by isuruf** [comment]
@ichumuh, can you try re-running your benchmark with jacobians with the latest commit of this PR?

**Comment by ichumuh** [comment]
@isuruf Thanks a lot!
The parameter is not yet exposed in the python wrapper, but I think cache is the default, which should be the option if want.
According to my Benchmark it seems to be about as fast as before you added the parameter to diff. `0.31`s before (got a new computer) and `0.37`s after.

**Comment by certik** [comment]
@ichumuh thanks for testing it. Does it mean that this PR does not work since it does not speed up your benchmark?

**Comment by ichumuh** [comment]
Sorry, with "before" I meant befor he added the parameter. I thought @isuruf wanted to see how his latest changes affected the runtime. This PR does work, the master branch is still very slow.

**Comment by isuruf** [comment]
Was there that much of a difference consistently? 0.31s vs 0.37s?

**Comment by ichumuh** [comment]
I tested both 3 times and it seems to be consistently slightly slower.

**Comment by isuruf** [comment]
@ichumuh, can you check now?

**Comment by ichumuh** [comment]
I can to a few more tests tomorrow, when I'm back in the office. I find it kinda odd that the benchmark, where I posted the code, got so much faster. It's all below 1s now, but took multiple seconds before. How is it possible, that my python stuff got a bit slower?

**Comment by isuruf** [comment]
> How is it possible, that my python stuff got a bit slower?

You mean from 0.31s to 0.37s?

**Comment by ichumuh** [comment]
> You mean from 0.31s to 0.37s?

Yes.

> @ichumuh, can you check now?

I'll do it tomorrow morning. (german time :))

**Comment by isuruf** [comment]
Earlier in this PR, caching was done within an expression. Later I implemented caching across expressions for matrices and jacobians where you differentiate multiple expressions w.r.t one variable.
I guess the caching across expressions might hurt you when the cache grows unbounded. We might need a LRU cache for caching across expressions. (That's not relevant to this PR)

**Comment by ichumuh** [comment]
> @ichumuh, can you check now?

It's now consistently between `0.31` and `0.32`.

**Pull request merged**
