### PR TITLE
has_symbol(): replace unnecessary RCP function arg

### PR DESCRIPTION
**Pull request by certik**
Added a few fixes on top of #1014.

### CODE REVIEW

**Comment by rwst** [comment]
Your additions are fine. Suggest to disable the codecov/patch test.

**Comment by isuruf** [comment]
@certik, you have to change the settings in https://codecov.io/account/gh/symengine/yaml to

```
coverage:
  ignore:
  - symengine/tests/.*
  - symengine/utilities/.*

  status:
    patch: false

comment: off
```

**Comment by certik** [comment]
Thanks for merging @rwst .

**Comment by certik** [comment]
@isuruf I made the change in codecov you requested.

**Comment by isuruf** [comment]
@rwst, is it okay if we turn codecov/patch back on? I was using the codecov chrome extension while reviewing PRs and now it's not working because codecov/patch was turned off.

**Comment by rwst** [comment]
I have no objections.

**Pull request merged**
