### PR TITLE
Use piranha and ecm from conda-forge

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
+1. How about Windows?

**Comment by isuruf** [comment]
piranha doesn't build with msvc with windows. ecm has msvc support, but it has to be added to conda-forge.

**Comment by certik** [comment]
Doesn't this make ECM work on Windows: https://github.com/conda-forge/ecm-feedstock/blob/8f20f657bf339023eaa5a97fef3daf7a66c6183d/recipe/build.sh ?

**Comment by isuruf** [comment]
Nope. that's for linux and osx. For windows, we have to use the visual studio build files provided

**Comment by certik** [comment]
I see. You are right. Here is an example of a Windows build: https://github.com/conda-forge/symengine-feedstock/blob/732910e73efc0e1e7c383368b2aa0ec29ca9c517/recipe/bld.bat

**Comment by certik** [comment]
Anyway, we don't need to test ECM on Windows, I forgot that we are not testing there anyway. 

But we use mpir on Windows I think, so we should use conda there.

**Comment by isuruf** [comment]
Yes, problem is that we'd need to have debug builds. (In windows to build symengine in debug mode, all the dependencies have to be compiled using debug mode.)
Also we are testing with MinGW and for Windows, dependencies have to be compiled with the same compiler. So, we'd need to handle that as well.

**Comment by certik** [comment]
Maybe we can use it for the Release mode only for now. And do the rest as we do now, until conda has a better support for it.  That way we have the infrastructure in, at least in Release mode.

**Pull request merged**
