### PR TITLE
[WIP] Trigonometric functions

### PR DESCRIPTION
**Pull request by abinashmeher999**

### CODE REVIEW

**Comment by certik** [comment]
Thanks for working on this.

**Comment by Sumith1896** [comment]
@abinashmeher999 Could you send this PR to the `symengine.rb` repo?
Thanks

**Comment by abinashmeher999** [comment]
@Sumith1896 Sure.

**Comment by isuruf** [comment]
This should be sent to https://github.com/symengine/symengine.rb

**Pull request closed without merging**
