### PR TITLE
Implement cancel method for polynomial

### PR DESCRIPTION
**Pull request by jmig5776**
In this Pull request a function **cancel** will be implemented for univariate polynomial.
Input and Output API currently is like
```
void cancel(const RCP<const Basic> &self, const RCP<const Basic> &other,
    const Ptr<RCP<const UIntPolyFlint>> &result_self, const Ptr<RCP<const UIntPolyFlint>> &result_other)
```
Main work is done in the PR #1620 Please go through this PR.
CC @certik @isuruf

### CODE REVIEW

**Comment by jmig5776** [comment]
Build has been terminated for external cause. I am closing and reopening this PR.

**Comment by jmig5776** [comment]
@certik The build is failing dont knw why?

**Comment by certik** [comment]
I don't know. The latest build seems to be running.

**Comment by certik** [comment]
Can you please squash the "Formatting" commit into the previous one? That was the point of this PR to have just one commit (or a few), but not any commits like fixing the formatting.

**Comment by jmig5776** [comment]
Okay

**Comment by jmig5776** [comment]
Done @certik

**Comment by jmig5776** [comment]
Ping @certik

**Comment by certik** [comment]
Thank you @jmig5776!

**Comment by jmig5776** [comment]
Thank you @certik @isuruf  For guiding me through this :smile:

**Pull request merged**
