### PR TITLE
Use inoutArg and Ptr

### PR DESCRIPTION
**Pull request by certik**
One should be using a pointer (`const Ptr<> &`, since we do not use raw pointers directly) for inout arguments, instead of just a reference (`&`).

Benchmarks do not seem to be affected.

Most people agree that pointer is better, though not all.

### CODE REVIEW

**Comment by isuruf** [comment]
+1

**Comment by certik** [comment]
Thanks @isuruf. To be honest I am leaning towards -1 actually. Overall, this is a relatively minor thing, but there are good arguments pro and against this change, I need to think about it more.

**Comment by abhinavagarwal07** [comment]
It is recommended to uses pointers instead of `non-const`reference.

**Comment by certik** [comment]
@abhinavagarwal07 some people recommend that, some people don't. I actually like non-const reference. It's perfectly safe, and simpler.

**Comment by rikardn** [comment]
@certik This PR is getting a bit old and you seem to have changed your mind. Is it ok to close?

**Comment by certik** [comment]
Yes, let's close it. I feel the `outArg` is more complicated and not really needed.

**Pull request closed without merging**
