### PR TITLE
Install CMake Find Modules

### PR DESCRIPTION
**Pull request by isuruf**
This first checks for pkgs like GMP with the absolute paths for when SymEngine was first installed, and then relative paths. User can give paths to GMP in the normal way for SymEngine (`GMP_DIR=`, `GMP_INCLUDE_DIRS=`, `GMP_LIBRARIES=`) as well

### CODE REVIEW

**Comment by certik** [comment]
Why does the Piranha test fail on Travis?

**Comment by isuruf** [comment]
Fixed it

**Comment by certik** [comment]
It looks good to me.

**Comment by certik** [comment]
There is still some boost problem in the Piranha test.

**Comment by isuruf** [comment]
Resolved them now

**Comment by certik** [comment]
I think this looks good, thanks!

**Pull request merged**
