### PR TITLE
Refactor: hide internal functions and remove unused operator<<

### PR DESCRIPTION
**Pull request by htfy96**
#839

### CODE REVIEW

**Comment by isuruf** [comment]
I'm wondering whether we need to have all the code shifted right for the anonymous namespace. Otherwise looks good to me. @certik, thoughts?

**Comment by htfy96** [comment]
@isuruf  Maybe we need a `.clang-format` that unifies style in all files.

**Comment by htfy96** [comment]
Indention removed.

**Comment by isuruf** [comment]
Thanks. @htfy96

**Comment by certik** [comment]
The PR is +1. Yes, we should use anonymous namespaces for things that are local to the file, that way it can't conflict or be used from other files by accident.

I usually don't indent inside a namespace I think. But it doesn't matter. Yes, we should use clang-format.

@htfy96 any ideas how we should use clang-format? Essentially I can't decide whether we should simply test it on Travis-CI, thus requiring every PR to be formatted using clang-format, or not.

When you code in C++, do you let the editor (vim in my case) automatically format it using clang-format?

**Comment by certik** [comment]
I guess clang-format already integrates with vim: http://clang.llvm.org/docs/ClangFormat.html#vim-integration as well as other editors, and read the configuration from `.clang-format`. I think we should start using clang-format, see how it goes and perhaps later enforce it on Travis-CI.

**Comment by htfy96** [comment]
@certik 

It seems that https://github.com/nest/nest-simulator/blob/master/build.sh and https://nest.github.io/nest-simulator/coding_guidelines_c++ provided a good example of static check.

**Comment by certik** [comment]
@htfy96 cool, thanks! I've created another issue #866 for this, let's discuss it over there.

**Pull request merged**
