### PR TITLE
Fix flint headers and replace use of deprecated funcs in flint2/3

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/symengine/symengine/issues/1983

### CODE REVIEW

**Comment by certik** [comment]
Will this work with all Flint versions or only 3.0?

**Comment by isuruf** [comment]
All flint versions.

**Review by certik — APPROVED** [review]
Awesome, looks great!

**Comment by chenrui333** [comment]
@isuruf and @certik, can we cut off a new release per this PR merge? Thanks! cc @HaoZeke 🙏

**Comment by certik** [comment]
Yes we can. @isuruf do you want to release symengine?

**Pull request merged**
