### PR TITLE
[skip ci] Add Siddharth, Tao and Chad to AUTHORS. Welcome to SymEngine !!

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@bollu, @sighingnow, @ivme, let me know if your names are correct.

**Comment by ivme** [comment]
Yup, Chad Mills is correct.  Thanks!

**Comment by bollu** [comment]
@isuruf - yep, correct. Thanks!

**Comment by sighingnow** [comment]
Correct, thanks @isuruf.

**Pull request merged**
