### PR TITLE
Misc parser

### PR DESCRIPTION
**Pull request by srajangarg**
Added some missing functionality to the parser, including multi argument function support. (and also some newly added functions)
Also added some tests to check if errors were being thrown correctly.
Also, the current master has trailing whitespaces, which I removed. Why are they creeping in (repeatedly), and why isn't travis reporting them?

### CODE REVIEW

**Comment by certik** [comment]
I think this looks great. Thanks.

I don't know why the whitespace check doesn't work, we need to fix it.

**Comment by Sumith1896** [comment]
Looks good to me too.

**Comment by Sumith1896** [comment]
Thanks @srajangarg 
Yes, we'll need to fix the whitespace thing.

**Comment by CodeMaxx** [comment]
I reviewed the whitespace checking code. The code is correct. I believe this has something to do with the  position of the code in `test_travis.sh`

**Comment by Sumith1896** [comment]
@CodeMaxx Possibly. Abhinav was trying the same here https://github.com/symengine/symengine/pull/827
Do send in a PR in case you fix it.

**Comment by CodeMaxx** [comment]
@Sumith1896 I tried placing the code in different positions in the file but no success. Could it be a problem with Travis?

**Comment by CodeMaxx** [comment]
Otherwise I think we should add a python script just like we had before.

**Pull request merged**
