### PR TITLE
Fixes memleak in LLVMDoubleVisitor

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/symengine/symengine/issues/1525

### CODE REVIEW

**Comment by bjodah** [comment]
Great!
Should we try setting `detect_leaks=1` in this PR?
https://github.com/symengine/symengine/blob/master/bin/test_travis.sh#L104
It had to be turned off earlier because it did report leak of llvm related resources:
<details>
<pre>
=================================================================
==64==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 237568 byte(s) in 14 object(s) allocated from:
    #0 0x534a18 in operator new(unsigned long) (/drone/src/github.com/bjodah/kinetgine/kinetgine/tests/test_kinetgine+0x534a18)
    #1 0x7f1bf8945ca1 in llvm::DenseMap<unsigned int, std::pair<unsigned short, unsigned short>, llvm::DenseMapInfo<unsigned int>, llvm::detail::DenseMapPair<unsigned int, std::pair<unsigned short, unsigned short> > >::grow(unsigned int) (/drone/symengine/lib/libsymengine.so.0.3+0xcb9ca1)

Indirect leak of 157472 byte(s) in 2 object(s) allocated from:
    #0 0x534a18 in operator new(unsigned long) (/drone/src/github.com/bjodah/kinetgine/kinetgine/tests/test_kinetgine+0x534a18)
    #1 0x7f1bf882dfca in llvm::X86TargetMachine::getSubtargetImpl(llvm::Function const&) const (/drone/symengine/lib/libsymengine.so.0.3+0xba1fca)

Indirect leak of 26624 byte(s) in 26 object(s) allocated from:
    #0 0x534a18 in operator new(unsigned long) (/drone/src/github.com/bjodah/kinetgine/kinetgine/tests/test_kinetgine+0x534a18)
    #1 0x7f1bf895d4f2 in llvm::LegalizerInfo::setAction(llvm::InstrAspect const&, llvm::LegalizerInfo::LegalizeAction) (/drone/symengine/lib/libsymengine.so.0.3+0xcd14f2)
...
</pre>
</details>

**Comment by isuruf** [comment]
Thanks for the suggestion. Let's see if errors show up.

**Comment by isuruf** [comment]
Tests pass

**Comment by bjodah** [comment]
that's great! merging (hope no one disapproves)

**Pull request merged**
