### PR TITLE
Add support for LLVM5

### LINKED ISSUE #1385: Support LLVM 5

### PR DESCRIPTION
**Pull request by bjodah**
To fix #1385.
Tests passes locally with LLVM 5.0.
I'm new to the LLVM toolchain so a careful review is probably in place.
Do we want to add LLVM 5 to the CI runs?

### CODE REVIEW

**Comment by isuruf** [comment]
@bjodah, thank you very much for doing this. I spent an evening trying to do this and it was way more complicated and segfaulted at the end.

Can you uncomment line 222 and send me the output for `cosh(x+y)`? I can check that with LLVM 4.0 to make sure it is correct.

**Comment by bjodah** [comment]
Sure, here's the program's source:
```
#include <symengine/llvm_double.h>

int main() {
    SymEngine::RCP<const SymEngine::Basic> x, y, r;
    x = SymEngine::symbol("x");
    y = SymEngine::symbol("y");
    r = SymEngine::cosh(SymEngine::add(x, y));
    SymEngine::LLVMDoubleVisitor v;
    v.init({x, y}, *r);
}
```

Here's my output for LLVM4.0:
```
LLVM IR
; ModuleID = 'SymEngine'
source_filename = "SymEngine"

; Function Attrs: nounwind uwtable
define internal void @0(double* nocapture readonly, double* nocapture) #0 {
EntryBlock:
  %2 = getelementptr double, double* %0, i32 0
  %3 = load double, double* %2
  %4 = getelementptr double, double* %0, i32 1
  %5 = load double, double* %4
  %6 = fadd double %5, %3
  %7 = tail call double @cosh(double %6)
  %8 = getelementptr double, double* %1, i32 0
  store double %7, double* %8
  ret void
}

; Function Attrs: nounwind
declare double @cosh(double) #1

attributes #0 = { nounwind uwtable }
attributes #1 = { nounwind }
```
and this is what I get with LLVM5.0:
```
LLVM IR
; ModuleID = 'SymEngine'
source_filename = "SymEngine"

; Function Attrs: nounwind uwtable
define internal void @0(double*, double* nocapture readonly) #0 {
EntryBlock:
  %2 = getelementptr double, double* %0, i32 0
  %3 = load double, double* %2
  %4 = getelementptr double, double* %0, i32 1
  %5 = load double, double* %4
  %6 = fadd double %5, %3
  %7 = tail call double @cosh(double %6)
  %8 = getelementptr double, double* %1, i32 0
  store double %7, double* %8
  ret void
}

; Function Attrs: nounwind
declare double @cosh(double) #1

attributes #0 = { nounwind uwtable }
attributes #1 = { nounwind }
```

note how **readonly** changed moved to the *second* argument.

Treating `F->addParamAttr` as 0-indexed gives the output:
```
LLVM IR
; ModuleID = 'SymEngine'
source_filename = "SymEngine"

; Function Attrs: nounwind uwtable
define internal void @0(double* nocapture readonly, double* nocapture) #0 {
EntryBlock:
  %2 = getelementptr double, double* %0, i32 0
  %3 = load double, double* %2
  %4 = getelementptr double, double* %0, i32 1
  %5 = load double, double* %4
  %6 = fadd double %5, %3
  %7 = tail call double @cosh(double %6)
  %8 = getelementptr double, double* %1, i32 0
  store double %7, double* %8
  ret void
}

; Function Attrs: nounwind
declare double @cosh(double) #1

attributes #0 = { nounwind uwtable }
attributes #1 = { nounwind }
```

**Comment by isuruf** [comment]
> Do we want to add LLVM 5 to the CI runs?

Yes please. Looks like we only test with LLVM on linux. Can you a test to an existing OSX test?

**Comment by bjodah** [comment]
Getting [an error](https://travis-ci.org/symengine/symengine/jobs/337175626#L2221) on osx:
```
+cmake -DCMAKE_INSTALL_PREFIX=/Users/travis/our_usr -DCMAKE_PREFIX_PATH=/Users/travis/our_usr -DCMAKE_BUILD_TYPE=Debug -DWITH_LLVM:BOOL=ON -DLLVM_DIR=/Users/travis/our_usr/share/llvm/ /Users/travis/build/symengine/symengine
dyld: Library not loaded: @rpath/libjsoncpp.0.dylib
  Referenced from: /Users/travis/our_usr/bin/cmake
  Reason: image not found
bin/test_travis.sh: line 100:  7274 Trace/BPT trap: 5       cmake $cmake_line ${SOURCE_DIR}
```
Surprised to see json being linked against, any idea how to troubleshoot?

**Comment by isuruf** [comment]
That's a bug with the conda-forge cmake package. Can you update the version of cmake installed?

**Comment by isuruf** [comment]
Thanks, I checked with a LLVM 6.0 nightly branch and it works there as well.

**Pull request merged**
