### PR TITLE
Fix comments

### PR DESCRIPTION
**Pull request by Marlin-Na**
It seems that these two comments are not valid anymore.

### CODE REVIEW

**Comment by certik** [comment]
Looking at the code:
```c++
CWRAPPER_OUTPUT_TYPE rational_set(basic s, const basic a, const basic b)
{
    if (not is_a_Integer(a) or not is_a_Integer(b)) {
        return SYMENGINE_RUNTIME_ERROR;
    }
    s->m = SymEngine::Rational::from_two_ints(
        *(rcp_static_cast<const Integer>(a->m)),
        *(rcp_static_cast<const Integer>(b->m)));
    return SYMENGINE_NO_EXCEPTION;
}
```
It seems it returns a `SYMENGINE_RUNTIME_ERROR` if `a` or `b` is not an `Integer`. The comment should be changed to "Returns SYMENGINE_RUNTIME_ERROR if either i or j is not an integer."

**Comment by certik** [comment]
The same thing with the other function:
```c++
CWRAPPER_OUTPUT_TYPE basic_diff(basic s, const basic expr, basic const symbol)
{
    if (not is_a_Symbol(symbol))
        return SYMENGINE_RUNTIME_ERROR;
    s->m = expr->m->diff(rcp_static_cast<const Symbol>(symbol->m));
    return SYMENGINE_NO_EXCEPTION;
}
```

Thanks for noticing that the comments are out-of-date.

If you change them per my last comment, then we can merge it.

**Comment by Marlin-Na** [comment]
Hi @certik , thanks for checking. I have added those comments with last commit.

**Comment by ShikharJ** [comment]
Looks good. Any objections @certik?

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
