### PR TITLE
safe accessors to Add::coeff_ and dict_

### PR DESCRIPTION
**Pull request by rwst**
Something like this is needed to provide SymPy's `x.as_coefficients_dict`, see https://github.com/symengine/symengine.py/issues/59

If you can think of a better interface, share your thoughts please.

### CODE REVIEW

**Comment by isuruf** [comment]
You could also return a `const umap_basic_num&`

**Comment by rwst** [comment]
That's better, yes.

**Comment by isuruf** [comment]
+1

**Comment by certik** [comment]
As [this](https://travis-ci.org/symengine/symengine/jobs/141271386) says, apply the following diff:
```diff
diff --git a/symengine/add.h b/symengine/add.h
index 6913b93..4bf0adb 100644
--- a/symengine/add.h
+++ b/symengine/add.h
@@ -73,7 +73,7 @@ public:
     {
         return coef_;
     }
-    const umap_basic_num& get_dict() const
+    const umap_basic_num &get_dict() const
     {
         return dict_;
     }
diff --git a/symengine/tests/basic/test_basic.cpp b/symengine/tests/basic/test_basic.cpp
index 6aac033..899e997 100644
--- a/symengine/tests/basic/test_basic.cpp
+++ b/symengine/tests/basic/test_basic.cpp
@@ -242,7 +242,7 @@ TEST_CASE("Add: basic", "[basic]")
 
     RCP<const Add> ar = rcp_static_cast<const Add>(r);
     REQUIRE(eq(*ar->get_coef(), *zero));
-    const umap_basic_num& addmap = ar->get_dict();
+    const umap_basic_num &addmap = ar->get_dict();
     auto search = addmap.find(x);
     REQUIRE(search != addmap.end());
     REQUIRE(eq(*search->second, *integer(2)));
```
Otherwise +1.

**Pull request merged**
