### PR TITLE
Infinity class

### PR DESCRIPTION
**Pull request by isuruf**
Replaces #916

TODO
- [ ] Use in functions and other places in symengine

### CODE REVIEW

**Comment by CodeMaxx** [comment]
@isuruf Ping me if you get any doubts in my code. I'm sorry I couldn't complete this. I got buzy in other stuff.But I hope I've laid down a good framework. Thanks for continuing this :)

**Comment by certik** [comment]
What are some examples where this would be used? I think we just need to use it at a few places to make sure things don't slow down and that we have implemented all important things. Then we can merge this and improve the rest in master.

**Comment by isuruf** [comment]
This can be used in places where we now throws errors. `tan(pi/2)` throws an error, but we can return `zoo` as in SymPy

**Comment by certik** [comment]
What does Mathematica and Maple do for `tan(pi/2)`?

**Comment by certik** [comment]
I see, Mathematica returns `ComplexInfinity`. Yes, we should do the same.

**Comment by CodeMaxx** [comment]
@isuruf I think you forgot to use `clangformat`

**Comment by certik** [comment]
+1 to merge.

**Comment by CodeMaxx** [comment]
Thanks for the merge!

**Pull request merged**
