### PR TITLE
Permit using an explicit location for gmp

### PR DESCRIPTION
**Pull request by coder0xff**

### CODE REVIEW

**Comment by isuruf** [comment]
You can give `GMP_LIBRARY` explicitly and CMake will use it.

**Comment by coder0xff** [comment]
I figured there had to be something like that.

**Comment by coder0xff** [comment]
Setting GMP_INCLUDE_DIRS and GMP_LIBRARIES as indicated in https://github.com/symengine/symengine/#external-libraries has no effect.

**Comment by certik** [comment]
@coder0xff Putting your desired GMP location into CMAKE_PREFIX_PATH should work. That is the preferred way you set libraries in cmake.

**Pull request closed without merging**
