### PR TITLE
Fix exp(x + num)/exp(x) not evaluating

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by rikardn** [comment]
I am curious about the rationale for doing this auto-simplification. To me it feels like a special case. Should also `pi**(x + n) / pi**n` be auto-simplified in the same way? And should we do `exp(x + n)/exp(x) = exp(n)` if n is an exact number automatically? I can see that this change follows what sympy does, I just cannot understand why.

**Comment by isuruf** [comment]
`pi**(x + n) / pi**x` is already simplified to be `pi**n` as does `E**(x + n) / E**x` to `E**n`. What this PR is doing is,
it's simplifying `E**n` when possible, but in master `E**(x + 0.2) / E**x` is given as `E**0.2`, but `E**0.2` is evaluated when constructed directly. This PR fixes this inconsistency.

**Comment by rikardn** [comment]
I'm sorry @isuruf, it was sympy that had the inconsistency I was referring to. I got my `import`s mixed up when testing this.

I guess we would still have the following inconsistency:

```python
symengine.pi**2.0
Out[1]: pi**2.0

symengine.E**2.0
Out[2]: 7.38905609893065
```

Are we sure that we want to do the auto-evaluation in the second example? Then we loose the option of evaluating the expression to a higher precision. Even if `2.0` might be a `RealDouble` it would be nice to have the option of evaluating to a higher precision. Even if using `RealMPFR(2.0)` I see that symengine is auto-evaluating to some precision. To me it seems as if `e**2.0` should be kept as it is.

**Comment by isuruf** [comment]
We should evaluate `pi**2.0` too, but that's outside the scope of this PR.
We evaluate things like `sin(2.0)`. Reason is that `2.0` is only accurate to 53 bits, so it doesn't make sense to evaluate `sin(2.0)` to more precision than the precision of `2.0`. That's one reason to do it. The other is that it prevents explosion of the symbolic tree.
So, the policy that symengine uses is that if you send in floating point number to a function like (sin, exp, etc) you get back a floating point number.

**Comment by rikardn** [comment]
Ok, this makes sense. Also using `RealMPFR` we get auto-evaluation to the precision we have requested.

```python
symengine.E**symengine.RealMPFR(1.0, prec=200)
Out[1]: 2.7182818284590452353602874713526624977572470936999595749670
```

Then there are other cases we should auto-evaluate like:

```python
symengine.E*2.0
Out[2]: 2.0*E
```

I can open an issue to remember these.

**Review by rikardn — APPROVED** [review]

**Pull request merged**
