### PR TITLE
Add Assumptions class

### PR DESCRIPTION
**Pull request by rikardn**
This PR adds the first version of an Assumptions class and use it in the `is_real` function.

* An assumptions object is constructed from symengine statements.
* The statements are parsed at construction into an internal form that is easier and faster to work with
* Methods on the assumptions object can be used to do basic queries on symbols. To for example check if a symbol is real.
* A function that wants to support assumptions can have an optional assumptions object argument.
* If no assumptions object is used default assumptions will be used

Benefits of design:
* Any symengine statements can be input as an assumption. The assumptions system can grow gradually and support more and more statements. For example `x > 0` would potentially mean that x is real and that x is positive and that x is non-negative
* Even though symengine statements are input to the assumptions object it is free to internally organize or cache the information in the most efficient way.
* Assumptions are not global state and can be optionally used by any function or method. Different function calls can use different assumptions.
* Assumptions are separated from the symbol objects
* Assumptions can be used both for query functions like `is_real` and for functions creating new expressions like `expand`.

Drawbacks of design:
* The assumptions object needs to be forwarded to all functions that need it. E.g `is_real` for matrices would need to take an assumptions argument and forward it to the scalar `is_real` function.
* more?

### CODE REVIEW

**Comment by isuruf** [comment]
Thansk @rikardn for working on this. I don't know enough about sympy's Assumptions system to review here. @certik?

**Review by certik — APPROVED** [review]
I think that this looks good as a design. What are "default assumptions"? I didn't see any defaults in the PR. I like that there are no globals and that they are not tied to the symbol classes in any way. Is there any performance overhead if assumptions are not used? It seems there shouldn't be based on the code.

Thanks for working on this! Let's also ask @isuruf for review. We can then gradually improve this to make it useful.

**Comment by certik** [comment]
The big mistake we did in SymPy is that we tied the assumptions with the symbols and the internal automatic simplification is depending on it.

As long as we approach assumptions as strictly an optional add on, not tied to the internal engine, then I think we are fine. It should still allow us to implement all the functionality that we need, without slowing SymEngine down if assumptions are not used.

**Comment by rikardn** [comment]
Thanks @certik for reviewing. 

The current performance penalty is when visiting a symbol:

```c++
void RealVisitor::bvisit(const Symbol &x)
{
    if (assumptions_) {
        is_real_ = assumptions_->is_real(x.rcp_from_this());
    } else {
        is_real_ = tribool::indeterminate;
    }
}
```

we need to check if we have an assumptions object or not. I opted for letting the default assumptions be represented with `nullptr` instead of a default assumptions object that would then be global and always needed when you don't want to use assumptions. In this example the default is the `else`, i.e. we don't know if this symbol is real or not. I don't have any ideas on how to avoid this if-statement.

**Comment by certik** [comment]
Where in SymEngine do we currently use `is_real`? I would assume that would be used in things like `refine(sqrt(x**2), assumptions)`, but I think we don't have that yet.

Just trying to evaluate which things get slower by this design.

**Comment by rikardn** [comment]
It is currenty used in `DenseMatrix::is_real` to check if all elements of a matrix are real. No assumptions are used there now, but I guess it would look something like: (I know that the default goes in the header file...)

```c++
tribool DenseMatrix::is_real(Assumptions *assumptions = nullptr) const
{
    auto A = *this;
    tribool cur = tribool::tritrue;
    for (auto &e : m_) {
        cur = and_tribool(cur, SymEngine::is_real(*e, assumptions));
        if (is_false(cur)) {
            return cur;
        }
    }
    return cur;
}
```

so there would be an added argument with a default nullptr that would be needed to be passed to the check for each element. Of course we should optimize this by only initializing the visitor once to only pass the assumptions pointer once. Something like:


```c++
tribool DenseMatrix::is_real(Assumptions *assumptions = nullptr) const
{
    auto A = *this;
    RealVisitor visitor(assumptions);
    tribool cur = tribool::tritrue;
    for (auto &e : m_) {
        cur = and_tribool(cur, visitor.apply(*e));
        if (is_false(cur)) {
            return cur;
        }
    }
    return cur;
}
```

(We might need to reset the visitor in the `apply` function.) So in total the `DenseMatrix::is_real` would need to always receive a `nullptr` when being called without assumptions and pass it once when creating the visitor. The visitor needs to check if it has assumptions whenever encountering a symbol (and potentially also in other cases). I think this is very cheap considering that `DenseMatrix::is_real` would very likely be called with some assumptions otherwise the `is_real` check doesn't do much when symbols are involved. I mean in the cases where assumptions would be taken they would very often be used. In the applications I work on myself I would probably always set all variables to be real and non-negative in one assumption object and then use that everywhere (perhaps via a context in symengine.py). Assumptions are incredibly useful.

I think the key here is, as you wrote @ondrej: we do not want to tie assumptions to the symbols and we do not want to use assumptions in the core, e.g. when doing auto-simplification (canonicalization).

**Comment by certik** [comment]
I think this design is solid. The core of symengine is not touched by this, and the only places that are influenced by this are places like `DenseMatrix::is_real` which would benefit from assumptions anyway, and the only overhead is one extra if statement check (I think). 

I don't see any downsides to this approach. Things can always be more tightly integrated in the future at the higher level, such the Python context and other ways, but as long as things stay decoupled at the lower level, I think we will not pay with any performance penalty.

+1 from me to merge.

Thank you @rikardn for working on this! Let me know if you want me to test or help with anything.

**Comment by rikardn** [comment]
Thanks @certik.

**Pull request merged**
