### PR TITLE
Move llvm_double.h implementation to a cpp file and add more functions

### LINKED ISSUE #1213: Add external functions to LLVMDoubleVisitor
Functions like `tan` are currently not implemented. To figure out how to do that, LLVM's code generators can be used.

```
#include <math.h>
double f() {
    return tan(2.0);
}
````

Compile to LLVM IR

    clang -S -emit-llvm test.cpp

Compile IR to C++ code to generate the IR

    llc -march=cpp -o test-gen.cpp test.ll

### PR DESCRIPTION
**Pull request by isuruf**
Fixes #1213

### CODE REVIEW

**Comment by ShikharJ** [comment]
I guess we need to have some tests for `abs` and `tan` in `test_lambda_double`. Otherwise +1.

**Comment by isuruf** [comment]
@ranjithkumar007, @ShikharJ can you have a look?

**Comment by jppelteret** [comment]
@isuruf Thanks a lot for adding all of the extra `LLVM`-related functions!

**Comment by isuruf** [comment]
Thanks for the reviews

**Pull request merged**
