### PR TITLE
[skip ci] Update AUTHORS

### PR DESCRIPTION
**Pull request by isuruf**
Added Pradyot, Nishant, malayaleecoder, Zhang, Zheng, Charles, Kunal, Rajith, Matthew, Iris, and James to AUTHORS. Welcome to SymEngine !

@pradyotprakash, @nishnik, @malayaleecoder, @codeworm96, @htfy96, @chenchfort, @kunal-iitkgp, @rajithv, @myluszczak, @irislq, @StoicBronco let me know if there needs to be any changes.

### CODE REVIEW

**Comment by Sumith1896** [comment]
Have a check people. We can merge this in 24 hours if no objections. 
cc @pradyotprakash, @nishnik, @malayaleecoder, @codeworm96, @htfy96, @chenchfort, @kunal-iitkgp, @rajithv, @myluszczak, @irislq, @StoicBronco

**Comment by malayaleecoder** [comment]
👍🏻 Thanks.

**Comment by irislq** [comment]
@isuruf Is it alright to modify the file directly or should I just say what to change my email to?

**Comment by isuruf** [comment]
I can edit it if you let me know the changes.

**Comment by irislq** [comment]
Thanks, I wanted to change my email to irislui66@gmail.com.

**Comment by isuruf** [comment]
@chenchfort, should I keep the gmail address or ucdavis address?

**Comment by chenchfort** [comment]
@isuruf I'd like to keep the gmail address.

**Comment by Sumith1896** [comment]
Thanks all!

**Pull request merged**
