### PR TITLE
added llvm support for floor and ceiling

### PR DESCRIPTION
**Pull request by ichumuh**
This is regarding #1521.
I think i've managed floor and ceiling. Not sure about sign and atan2, seems like they are not supported by llvm?

### CODE REVIEW

**Comment by isuruf** [comment]
I've added support for atan2 and sign. Can you add tests?

**Comment by certik** [comment]
Thanks @ichumuh and @isuruf for the improvements.

@ichumuh would you please mind adding tests for these?

**Comment by ichumuh** [comment]
@isuruf Thanks!
@certik I'll see to that next week.

**Comment by ichumuh** [comment]
1. So I've tried to create the tests and I think I have to extend [https://github.com/symengine/symengine/blob/master/symengine/tests/eval/test_lambda_double.cpp](url) right?
The tests seems to compare llvm with lambda results, but my pull request only contains llvm implementations. So I've tried to implement the lambda stuff as well, as you can see in my latest commit. But it doesn't compile because `floor` `ceil` and `<` are not defined for complex numbers. How do I deal with this? Does llvm even work with complex numbers?

2. I think we can not use copysign in the llvm version because it does not handle 0 correctly. This is also why my lambda version is different.

**Comment by isuruf** [comment]
> How do I deal with this? 

Move the implementations to `LambdaRealDoubleVisitor` which is only for reals.

> I think we can not use copysign in the llvm version because it does not handle 0 correctly. This is also why my lambda version is different.

I think that's fine as floating point numbers are signed and there's positive and negative zeros. I would change the LambdaRealDoubleVisitor implementation to be `(x >= 0.0) ? 1.0 : -1.0`

**Comment by isuruf** [comment]
On second thought, since sympy gives 0.0, so we should do the same.

**Comment by ichumuh** [comment]
> Move the implementations to LambdaRealDoubleVisitor which is only for reals.

Thanks, I'll do that. 

> On second thought, since sympy gives 0.0, so we should do the same.

This is also the proper signum definition.

**Comment by isuruf** [comment]
Fixed the sign implementation to return 0 for 0.

**Comment by ichumuh** [comment]
@isuruf @certik I've added the implementations for sign, floor and ceiling for lambda. Then I've added the new functions to the tests that compare llvm and lambda. Is this what you had in mind?

There is also a problem with the `REQUIRE(::fabs((d - d2) / d) < 1e-12)` checks, because for ceiling `d==0`. Why do you divide by `d`?

**Comment by ichumuh** [comment]
When I try to use sign in symengine.py like this
`se.Lambdify([a], se.sign(a), backend='llvm', cse=True, real=True)(3.001)` I get the following error:
`LLVM ERROR: Program used external function 'symengine_sign_internal' which could not be resolved!`
Are there any related tests in symengine.py, where I can add the new functions? I didn't find any.

**Comment by isuruf** [comment]
Thanks for checking. Rewriting `Sign` as a `Piecewise` is another option we could try.

**Comment by ichumuh** [comment]
like this?

**Comment by isuruf** [comment]
Looks good to me. Can you apply the diff at https://travis-ci.org/symengine/symengine/jobs/505730718#L730-L771 for formatting?

**Comment by ichumuh** [comment]
Thanks! Can you please update symengine_version.txt in symengine.py?

**Comment by certik** [comment]
@ichumuh you can send a PR updating it.

**Pull request merged**
