### PR TITLE
Permit using explicit locations for GMP

### PR DESCRIPTION
**Pull request by coder0xff**

### CODE REVIEW

**Comment by isuruf** [comment]
See the updated README. you can use `GMP_LIBRARY` to do the same thing.

**Comment by coder0xff** [comment]
Does this also support setting the include directory?

**Comment by isuruf** [comment]
GMP_INCLUDE_DIR should work. We should update the README to reflect that.

**Comment by coder0xff** [comment]
Cool. Thanks.

**Pull request closed without merging**
