### PR TITLE
Use lrzip for Sage tarball

### PR DESCRIPTION
**Pull request by certik**
TODO:

* [x] This currently depends on https://github.com/travis-ci/apt-package-whitelist/issues/776 to get fixed. It might take a week or two.

### CODE REVIEW

**Comment by certik** [comment]
So this works, but it seems surprisingly to be slower than using the tar.gz...

**Comment by certik** [comment]
I made a polished patch out of this. The previous timing (before rebase) was 2m 52s to download and unpack (https://travis-ci.org/sympy/symengine/jobs/75979744). It probably won't change after the rebase. This is to be compared against the current master that uses tar.gz, here are some representative times:

2m 1s (https://travis-ci.org/sympy/symengine/jobs/75959789)
1m 52s (https://travis-ci.org/sympy/symengine/jobs/75476398)
1m 45s (https://travis-ci.org/sympy/symengine/jobs/75608491)
2m 56s (https://travis-ci.org/sympy/symengine/jobs/75752147)
2m 0s (https://travis-ci.org/sympy/symengine/jobs/75830130)
1m 43s (https://travis-ci.org/sympy/symengine/jobs/75942947)

So it varies a lot, but it seems that 1m45s is no exception. We'll see how the lrzip does.

**Comment by certik** [comment]
The failures are weird, they seem all unrelated. I restarted the OS X failures, but it didn't help.

**Comment by isuruf** [comment]
Using lrzip in https://github.com/symengine/symengine.py as there is no longer a .tar.gz package

**Pull request closed without merging**
