### PR TITLE
Check for flint-arb

### PR DESCRIPTION
**Pull request by isuruf**
cc @mkoeppe

### CODE REVIEW

**Comment by mkoeppe** [comment]
This works well - https://github.com/mkoeppe/sage/runs/2156547007

**Review by lkeegan — APPROVED** [review]
@isuruf re the codecov upload issue, it seems related to codecov using the github actions job id to authenticate the upload, as they also check that the job is not stale, and since both jobs that upload have the same name it could be that they end up checking the wrong one when the slower job tries to upload?.. 
hopefully using a token for the upload instead will work better: #1752

**Comment by mkoeppe** [comment]
This works well on `ubuntu-groovy`, where Sage uses the system library for arb - see https://github.com/mkoeppe/sage/runs/2156547115

**Comment by isuruf** [comment]
Thanks @mkoeppe, @lkeegan for the review. Yeah, let's try the codecov PR.

**Pull request merged**
