### PR TITLE
add support for LLVM 10

### PR DESCRIPTION
**Pull request by lkeegan**
- requires c++14: add WITH_CPP14 option to CMake
  - llvm::make_unique has been removed: alias it to std::make_unique

### CODE REVIEW

**Comment by certik** [comment]
@lkeegan thank you! 

Do you know why the `make_unique` must be defined in the `llvm` namespace? That seems discouraged I think to define new things in other namespaces, isn't it? Is it SymEngine or LLVM that requires it? If you can describe the actual problem, I think there might be a better solution.

**Comment by lkeegan** [comment]
@certik llvm previously used c++11, which doesn't have `std::make_unique`, so they implemented their own `llvm::make_unique`, which you use here:

https://github.com/symengine/symengine/blob/fc05f8d55915c2de956e7797d764eb1116b61711/symengine/llvm_double.cpp#L194

https://github.com/symengine/symengine/blob/fc05f8d55915c2de956e7797d764eb1116b61711/symengine/llvm_double.cpp#L960

From llvm version 10 they are using c++14, which does have `std::make_unique`, so they have removed `llvm::make_unique`.

So the problem is just that `llvm::make_unique` should be replaced with `std::make_unique` when using llvm 10.

**Comment by certik** [comment]
@lkeegan please ping me once tests pass, and we can merge it.

**Comment by lkeegan** [comment]
ping @certik

**Comment by certik** [comment]
Thanks @lkeegan, I really appreciate your PR. Let us know if anything else does not work.

**Comment by lkeegan** [comment]
thanks @certik !

**Pull request merged**
