### PR TITLE
[WIP] Series Expansion

### PR DESCRIPTION
**Pull request by isuruf**
TODO
- [x] Use faster expansion for `sin(p)`, `cos(p)`, etc.
- [x] Add tests for series expansion
- [x] dependency on #753 
- [ ] Remove 1086ffd4481c3e93d72d5fe80b4d92dc5fbe14b9 from this PR
- [ ] Add tests for series addition, multiply, etc.

### CODE REVIEW

**Comment by rwst** [comment]
As to direct substitution: in `ring_series` there is a hardcoded limit for the poly size up to which the method is applied (`20`) so they might have done tests to determine that it only is faster than the calculus formulae when the poly is smaller. Maybe this varies from function to function. Have you tested if direct substitution speeds up `exp/log()` too?

**Comment by isuruf** [comment]
I checked only `exp` and direct substitution is slower for `exp(cos(x+1))`.

**Comment by rwst** [comment]
Do you intend to keep two implementations or do you propose to remove `expand.cpp`?

**Comment by isuruf** [comment]
I'm proposing to remove `expansion.cpp`, but after checking that there's no overhead introduced.

**Comment by rwst** [comment]
Then the tests from the expansion version should be adapted to the new version.

**Comment by certik** [comment]
The failure is that you don't install `series_visitor.h`. Looks like our new tests work. :)

**Comment by certik** [comment]
@isuruf I think this branch is all messed up for some reason, it's showing some old commits.

**Comment by isuruf** [comment]
I'll fix that

**Comment by rwst** [comment]
I'm in the process of adapting the test file and get test errors. The first is from the expression `pow(sub(four, x), rational(1, 2));` (=`sqrt(4-x)`) which should result in `2 - 1/4*x - 1/64*x^2 - 1/512*x^3 -
`:
```
4**(1/2)+(-1/8)*4**(1/2)*x+(-1/128)*4**(1/2)*x**2+(-1/1024)*4**(1/2)*x**3+
```

**Comment by isuruf** [comment]
First error is because SymEngine hasn't implemented nth_root. I implemented several methods to factorize numbers in `ntheory.h` a long time ago, but I didn't have time then to make one `factorize` method that would combine the several methods implemented.

Second and third errors are due to a change I did in fd831a5. All the calls like `pow(var, i, i)` should be changed to `pow(var, i, i+1)`.

**Comment by rwst** [comment]
After merging recent master this branch no longer compiles, due to 6201e78. I'm on it.

**Comment by rwst** [comment]
`atanh` still fails. I have added factorization to the TODO but can we not specialize to use GMP's `nth_root` with ints and rats?

**Comment by isuruf** [comment]
@rwst, I fixed `atanh` and `cot(sin(x))` errors.
About nth root, you mean keep `sqrt(8)` as it is, but simplify `sqrt(16)` to 4? If so, that will be easier to implement.

**Comment by rwst** [comment]
Simplify yes but with non-powers it depends what series coefficient ring you have. So you have different implementations of `Series::root`. And some will have to throw an error if there is no root in the ring.

**Comment by rwst** [comment]
See #751 for additional commits.

**Comment by rwst** [comment]
The test fail is `4**(1/2)` not simplifying in `sqrt(4-x)`.

**Comment by rwst** [comment]
Problems with the MS OS, maybe you need to `#include <sstream>` in `printer.cpp`.

**Comment by rwst** [comment]
What's the reason for not using `Series:pow` in `Seriesbase::pow` (while you are using `Series::mul` in `Seriesbase::mul`). This way you won't benefit from Piranha/Flint poly power code when calling `series.pow(Number)` if I'm not mistaken.

**Comment by isuruf** [comment]
You are right. I'll special case it for `Integer`

**Comment by rwst** [comment]
Can you also please add blank lines between functions in `series_piranha.cpp`?

**Comment by rwst** [comment]
The exponent doesn't seem right: https://github.com/symengine/symengine/pull/710/files#diff-8c57b10e435f746334432ad7ec8dbf1dR137

**Comment by rwst** [comment]
Thanks for the work!

**Pull request merged**
