### PR TITLE
Add Parser support for sign

### PR DESCRIPTION
**Pull request by MinnieMouse11**

### CODE REVIEW

**Comment by bjodah** [comment]
This will need a test.

**Comment by MinnieMouse11** [comment]
> This will need a test.

added :)

**Comment by bjodah** [comment]
This looks good! Thank you.

**Comment by MinnieMouse11** [comment]
Hi @certik, Can you please have a look?

**Comment by rikardn** [comment]
It seems as if I cannot merge this since there is a test that fails. This failure is unrelated to this PR. Is this a new setting in github? Has anyone looked into the failing test?

**Comment by MinnieMouse11** [comment]
still failing on the same test..

**Comment by EinavS1** [comment]
Hi @isuruf, can you please have a look?
I believe the expected checks not running should be solved by @lkeegan fix here- https://github.com/symengine/symengine/pull/2049#issuecomment-2362917010

**Comment by MinnieMouse11** [comment]
Hi @isuruf , can you please have a look?
I believe the expected checks not running should be solved by @lkeegan fix here- https://github.com/symengine/symengine/pull/2049#issuecomment-2362917010

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
