### PR TITLE
recursively check for missing headers in install in CI

### PR DESCRIPTION
**Pull request by lkeegan**
- add missing headers to cmake install
- see #1950

### CODE REVIEW

**Comment by rikardn** [comment]
So the idea is that the tests should currently fail with this PR right?

**Comment by lkeegan** [comment]
@rikardn I also added the missing headers to CMakeLists

**Comment by rikardn** [comment]
Ok. Will we also get an error in the other direction? I mean if a header file has been removed but is still in the CMakeLists?

**Comment by lkeegan** [comment]
Yes the `make install` command will fail if you include a file in CMakeLists that doesn't exist, e.g.
```
CMake Error at symengine/cmake_install.cmake:394 (file):
  file INSTALL cannot find "/home/lkeegan/SSC/symengine/symengine/refineQ.h":                                                                                                                                                                       
  No such file or directory.                                                                                                                                                                                                                        
Call Stack (most recent call first):                                                                                                                                                                                                                
  cmake_install.cmake:73 (include) 
```

**Review by rikardn — APPROVED** [review]

**Comment by lkeegan** [comment]
@rikardn thanks for reviewing!

**Pull request merged**
