### PR TITLE
Replace nonius with google benchmark

### PR DESCRIPTION
**Pull request by lkeegan**
advantages of google benchmark vs nonius:
- more reliable timings (e.g. https://github.com/symengine/symengine/pull/1684#issuecomment-685559163)
- more actively maintained (e.g. nonius gives compilation errors with c++20)
- more results, e.g. asymptotic complexity estimate, statistical significance of changes in benchmark results

`./benchmarks/bench` sample output:
```
------------------------------------------------------
Benchmark            Time             CPU   Iterations
------------------------------------------------------
expand1/2         3170 ns         3170 ns       219872
expand1/4        23109 ns        23109 ns        30342
expand1/8       194034 ns       194027 ns         3621
expand1/16     1411263 ns      1411212 ns          509
expand1/32     8642076 ns      8642034 ns           80
expand1/64   100402653 ns    100398590 ns           10
expand1_BigO     381.16 N^3      381.15 N^3  
expand1_RMS          9 %             9 %    
expand2/2        49367 ns        49366 ns        14154
expand2/4       788289 ns       788266 ns          877
expand2/8     17832274 ns     17832193 ns           39
expand2/16   641907184 ns    641898998 ns            1
expand2_BigO  154805.63 N^3   154803.66 N^3  
expand2_RMS         19 %            19 %    
expand3/2         3095 ns         3095 ns       224329
expand3/4        15044 ns        15044 ns        46945
expand3/8        53526 ns        53526 ns        13137
expand3/16      282879 ns       282872 ns         2482
expand3/32     1191834 ns      1191794 ns          598
expand3/64     4709946 ns      4709891 ns          149
expand3/128   18359872 ns     18359447 ns           39
expand3_BigO    1122.46 N^2     1122.44 N^2  
expand3_RMS          1 %             1 %    

```

`./benchmarks/bench_eval_double` sample output:
```
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
eval_double/2                            860 ns          860 ns       801858
eval_double/8                           3406 ns         3406 ns       201721
eval_double/64                         27796 ns        27795 ns        25215
eval_double/512                       233934 ns       233929 ns         2937
eval_double/4096                     1987138 ns      1987067 ns          359
eval_double/16384                   13565917 ns     13564287 ns           57
eval_double_BigO                       58.32 NlgN      58.31 NlgN 
eval_double_RMS                           14 %            14 %    
eval_double_visitor_pattern/2            861 ns          861 ns       806550
eval_double_visitor_pattern/8           3465 ns         3465 ns       203680
eval_double_visitor_pattern/64         29034 ns        29033 ns        24023
eval_double_visitor_pattern/512       241835 ns       241830 ns         2874
eval_double_visitor_pattern/4096     2011685 ns      2011647 ns          355
eval_double_visitor_pattern/16384   13727692 ns     13727077 ns           54
eval_double_visitor_pattern_BigO       59.01 NlgN      59.01 NlgN 
eval_double_visitor_pattern_RMS           14 %            14 %    
eval_double_single_dispatch/2            800 ns          800 ns       853215
eval_double_single_dispatch/8           3363 ns         3362 ns       209117
eval_double_single_dispatch/64         27711 ns        27711 ns        25152
eval_double_single_dispatch/512       273880 ns       273872 ns         2557
eval_double_single_dispatch/4096     2414245 ns      2414129 ns          294
eval_double_single_dispatch/16384   15093245 ns     15092873 ns           48
eval_double_single_dispatch_BigO       65.07 NlgN      65.07 NlgN 
eval_double_single_dispatch_RMS           11 %            11 %    
```

### CODE REVIEW

**Review by rikardn — APPROVED** [review]
I like this change!

**Comment by rikardn** [comment]
I think that we can merge this. Google benchmark is quite actively developed. I cannot see any downsides.

**Comment by certik** [comment]
Thanks! I need to test google benchmarks more. This change looks fine to me. Thanks for that assembly analysis in https://github.com/symengine/symengine/pull/1684#issuecomment-685559163. 

Benchmarking is really tricky to get right and for that reason I simply benchmarked things by hand mostly when developing symengine because I do not trust any library. And doing it by hand I learned what the timings should be (and that took time to ensure the timings can be trusted) on my computer and I could spot a change right away. When relying on any 3rd party library, one must spend a long time to ensure the timings can be trusted, and as you found out, sometimes they cannot.

**Comment by rikardn** [comment]
Thanks for the comment @certik. We should keep this in mind.

**Comment by lkeegan** [comment]
@certik google benchmark has the advantage of a fairly large user base & that it is actively maintained (it also offers some useful functions to [prevent the compiler from optimizing away the benchmarks](https://github.com/google/benchmark/blob/main/docs/user_guide.md#preventing-optimization)) - but I definitely agree there is no easy solution for benchmarking!

**Comment by certik** [comment]
@lkeegan thank you for switching the benchmarks. I agree with the switch. Given that google benchmarks seem to have a fairly large user base, it is worth to learn how to use them and when they can be trusted.

**Pull request merged**
