### PR TITLE
Use const references

### PR DESCRIPTION
**Pull request by mafiya69**
I think 
```
for (auto& name : ds) {
    ...
}
```
can be replaced with 
```
for (const auto& name : ds) {
    ...
}
```
if `name` is not modified in `for` loop.

### CODE REVIEW

**Comment by certik** [comment]
Excellent, good point. +1 to merge if tests pass.

**Comment by Sumith1896** [comment]
+1

**Comment by Sumith1896** [comment]
Thanks @mafiya69 
Good job.

**Comment by certik** [comment]
Thanks @mafiya69, indeed very good job.

**Pull request merged**
