### PR TITLE
use auto, ranged-based loops (clang-modernize 3.7)

### PR DESCRIPTION
**Pull request by rwst**

### CODE REVIEW

**Comment by rwst** [comment]
I do not understand the Travis error.

**Comment by isuruf** [comment]
That's an error because of failed `apt-get` commands

**Comment by isuruf** [comment]
+1

**Comment by certik** [comment]
@rwst is this what `clang-modernize` suggested? Those are good changes.

**Comment by rwst** [comment]
@certik yes I transformed already Pynac to C++11 with this. It takes a long time but it's very good.

**Comment by certik** [comment]
Nice. I think we already use modern C++11, but sometimes we slip.

**Pull request merged**
