### PR TITLE
has_symbol(): replace unnecessary RCP function arg

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by rwst** [comment]
Compile fail because apparently Ptr must be initialized.

**Comment by certik** [comment]
I see -- I only tested in Debug mode, which uses Teuchos, whose Ptr is a bit more general (and perhaps slower). SymEngine's Ptr is more restrictive. This should fix it.

**Comment by rwst** [comment]
I think #1014 has a cleaner solution.

**Comment by certik** [comment]
I agree. Let's keep this open just to make sure tests pass. But then close it in favor of #1014, which is cleaner, because it doesn't need to initialize the Ptr to null, and then assign something else to it.

**Comment by Sumith1896** [comment]
https://github.com/symengine/symengine/pull/1016 got merged

**Pull request closed without merging**
