### PR TITLE
Restructure printing code

### PR DESCRIPTION
**Pull request by isuruf**
A user would normally need `symengine/printers.h`

An advanced user would need `symengine/printers/strprinter.h` or `symengine/printers/mathml.h`

### CODE REVIEW

**Comment by bjodah** [comment]
+1 from me

**Comment by certik** [comment]
The disadvantage of `strprinter.cpp` is that I think the compiler can't inline the method calls now, but we would have to benchmark it to see. This can be fixed by moving the methods implementation into a header file `strprinter-incl.h`, which will get included at the bottom of `strprinter.h`. That way users don't have to see the implementation, but the compiler can still inline it.

**Comment by bjodah** [comment]
Shouldn't link time optimization sort that out? (compiling with `-flto`)

**Comment by certik** [comment]
Can `-flto` even be used when we create an so library, say, for Python?

**Comment by bjodah** [comment]
I believe so, pybind11 even uses it [by default](https://pybind11.readthedocs.io/en/stable/compiling.html). But I'm no expert on the matter...

**Comment by isuruf** [comment]
Compiler can't inline the methods, because the `visit` methods are virtual methods.

**Comment by certik** [comment]
Actually the `bvisit` methods are static, not virtual, called from here:

https://github.com/symengine/symengine/blob/832ab177f164664c896278f1680c4db76b179fef/symengine/visitor.h#L68

and when we designed this, one of the ideas was that the compiler can inline the `bvisit` methods. With this PR, it can't, unless LTO is used.

**Pull request merged**
