### PR TITLE
Drop WITH_CPP14 flag

### PR DESCRIPTION
**Pull request by isuruf**
And also use `CMAKE_CXX_FLAGS` where appropriate.

### CODE REVIEW

**Comment by isuruf** [comment]
@bjodah, can you check that this works?

**Comment by bjodah** [comment]
sure, I'll get right back to you.

**Comment by isuruf** [comment]
Thanks for checking.

**Comment by certik** [comment]
That looks good.

(Overall I am not happy with how complicated our CMake configuration has become, but I don't know a way to significantly simplify it.)

**Pull request merged**
