### PR TITLE
Number Wrapper

### PR DESCRIPTION
**Pull request by isuruf**
NumberWrapper would act like `numeric` in Pynac and FunctionSymbol will be used to create wrappers to SymPy functions.

### CODE REVIEW

**Comment by certik** [comment]
Can you add a test where in the test file you subclass NumberWrapper, provide some kind of `eval` function and test that things evaluate properly?

**Comment by certik** [comment]
Otherwise it looks good.

**Comment by isuruf** [comment]
Added a test case

**Comment by certik** [comment]
+1 to merge if tests pass.

**Comment by isuruf** [comment]
It seems `std::stol` is not defined in MinGW. I'll add a workaround.

**Comment by certik** [comment]
Looks very good to me. We have robust tests, that catch such errors, I like it.

**Pull request merged**
