### PR TITLE
Install specific piranha version

### LINKED ISSUE #1091: Travis: Install a specific Piranha version
Currently we always install the latest version, which then sometimes breaks things, e.g. here:

https://travis-ci.org/symengine/symengine/jobs/167098984#L382

the failure is caused by Piranha now requiring cmake 3.0.

The solution is to checkout a specific git version, so that our tests are reproducible and don't change. Then from time to time we upgrade to a newer Piranha version and fix tests if needed.

### PR DESCRIPTION
**Pull request by CodeMaxx**
Fixes #1091 

@certik  @isuruf

### CODE REVIEW

**Comment by CodeMaxx** [comment]
https://github.com/travis-ci/travis-ci/issues/6307

**Comment by certik** [comment]
+1 to merge if tests pass.

**Comment by CodeMaxx** [comment]
@certik I think there is some problem with Travis... see the issue I linked to in the previous comment.

**Comment by CodeMaxx** [comment]
I think this is not required after #1093

**Pull request closed without merging**
