### PR TITLE
add erf and erfc in evaluate class

### LINKED ISSUE #1187: Functions "erf" and "erfc" missing in Evaluate class
As the title says, `erf` and `erfc` functions are missing in the `Evaluate` class. Without these (and their automatic evaluation) its not possible to evaluate the result of these functions called with a custom number class derived from `NumberWrapper`.

Relates to #1185

### PR DESCRIPTION
**Pull request by ranjithkumar007**
@isuruf  @jppelteret  i couldn't find function like mpc_erf or mpc_erfc in [docs](http://www.multiprecision.org/index.php?prog=mpc&page=html#Function-Index) .
Fixes #1187

### CODE REVIEW

**Comment by jppelteret** [comment]
Thanks a lot for adding this functionality @ranjithkumar007!

**Comment by jppelteret** [comment]
Does this perhaps need at least one test for real doubles in `test_functions.cpp `?

**Comment by ranjithkumar007** [comment]
yes @jppelteret  ..will add it asap.

**Comment by isuruf** [comment]
@ranjithkumar007, can you remove binary file `symengine/tests/basic/test_nan`? You need to completely remove it from history. See this article, https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by ranjithkumar007** [comment]
ping @isuruf

**Comment by isuruf** [comment]
@ranjithkumar007, can you fix the merge conflicts?

**Comment by ranjithkumar007** [comment]
updated @isuruf

**Comment by jppelteret** [comment]
Thanks very much to you both :-)

**Comment by isuruf** [comment]
@certik, I forgot to check that the binary file was removed from history and it wasn't. Shall I force push to correct this?

**Pull request merged**
