### PR TITLE
Add Ziyi, Andreas, Kieran, Clouds, Sylvain and Alan to AUTHORS.

### PR DESCRIPTION
**Pull request by isuruf**
Welcome to SymEngine!

@clouds56, @ahumenberger, @KKaempen, @SylvainCorlay, @ladrift, can you please let us know if you want to change your name or email address here?

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Sounds good to me.

**Comment by isuruf** [comment]
cc @alanlh

**Comment by clouds56** [comment]
Looks good to me.

**Comment by certik** [comment]
Thanks. I am going to merge this. If anyone wants to change their name or address, we can do it in another PR.

**Pull request merged**
