### PR TITLE
Add var_ and degree_ to SeriesCoeffInterface

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
Shouldn't we rather add some accessor methods and keep the variables
private?

**Comment by rwst** [comment]
I agree with @certik . While there is https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rh-get
the discussion at https://github.com/isocpp/CppCoreGuidelines/issues/507 shows the item is named wrongly. Also the class is abstract (also implied by "Interface"), and so shouldn't have state.

Further, I think the variables should be `const`: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rconst-const

**Comment by certik** [comment]
I think you still need to use the accessors in the Piranha module.

**Comment by isuruf** [comment]
Done

**Comment by rwst** [comment]
I don't like the `protected` usage but I would be satisfied if you made the variables `const` which works nicely here because they are intitialized on construction.

**Comment by rwst** [comment]
Thanks, LGTM.

**Pull request merged**
