### PR TITLE
Add polygonal numbers and polygonal roots functions

### PR DESCRIPTION
**Pull request by rikardn**
Mathematica has PolygonalNumber: https://reference.wolfram.com/language/ref/PolygonalNumber.html
The polygonal root is the inverse: http://oeis.org/wiki/Polygonal_numbers#Polygonal_roots

### CODE REVIEW

**Comment by rikardn** [comment]
I have separated the numeric calculation from the symbolic in this PR. For this particular PR it is a minor thing, but I think for other number theoretic functions that are slow and difficult to calculate numerically similar separations would come with a number of benefits:

1. The numeric calculation could be used stand alone.
2. The numeric caluculations could be imported and wrapped from other libraries in the future.
3. For functions very slow to calculate like the mertens function we could set a limit on the "auto-calculation", defer the calculation and let a future `doit` function do the actual calculation. For example `M(1000000000000)` would take a long time to calculate and could be kept unevaluated until `doit` is called on the expression. This way expressions like `M(1000000000000) * x` would be super fast and if x is substituted for 0 in the future the calculation of M would never be needed.
4. The current `ntheory.cpp` is a mix of pure numeric and "semi-symbolic" functions. It would be easier to find and use the functions if they would be clearly separated.

**Comment by rikardn** [comment]
This is ready for review

**Comment by isuruf** [comment]
What's the name that sympy use? I can't find it in sympy

**Comment by rikardn** [comment]
It is not available in sympy as far as I know. It is in mathematica though (except for the root). See the links above.

**Comment by isuruf** [comment]
Thanks. Can you add these links in the code comments as well?

**Comment by rikardn** [comment]
Sure! Good point.

**Comment by rikardn** [comment]
Sorry, did a bad merge.

**Comment by rikardn** [comment]
Should be good now. Fixed bad merge and squashed commits. Also added function documentation with the references above.

**Pull request merged**
