### PR TITLE
Add modulo operator as a two argument function "Mod"

### PR DESCRIPTION
**Pull request by bjodah**
I wanted to evaluate an expression with the modulo operator using our LLVM backend, it doesn't look like we have support for it, so I added it in this PR. There are multiple variants of the modulo operator (c.f. https://en.wikipedia.org/wiki/Modulo_operation), here I took the pragmatic approach that `Mod` should match `fmod`.

This might not be what we want because this would deviate from SymPy's `Mod` which has a different behavior than `fmod`:
```python
>>> for a, b in [((-1)**i, (-1)**j) for i in range(2) for j in range(2)]:
...     print(sympy.Mod(a*3.1, b*2.0), math.fmod(a*3.1, b*2.0))
... 
1.10000000000000 1.1
-0.900000000000000 1.1
0.900000000000000 -1.1
-1.10000000000000 -1.1
```
Should I rename `Mod` in this PR to e.g. `TruncMod` or `ModTrunc` or `FMod` or something else?

Other things to note:
- The canonicalizing function `mod` only handles integer coefficients right now and can probably be improved.

### CODE REVIEW

**Comment by isuruf** [comment]
I think we should have `Mod` with a rounding mode and the default will be `trunc` in C++ and `floor` in Python.

**Comment by isuruf** [comment]
Or maybe two different classes.

**Comment by bjodah** [comment]
@isuruf yes, I went with two classes `TruncMod` and `FloorMod`, that way we also leave the door open for the two other variants in the future.

What's the plan for c++17 in SymEngine? I put a `if constexpr` in here, is it too soon for upping the requirements to c++17? (personally I think it's about time to move on since it makes for a vetter development experience). If we need c++14 I guess I'll do some template meta programming shenanigans instead...

**Comment by bjodah** [comment]
I'm deferring this for now. Using `floor` can emulate Mod.

**Pull request closed without merging**
