### PR TITLE
MyBinder support

### PR DESCRIPTION
**Pull request by isuruf**
See https://mybinder.org/v2/gh/isuruf/symengine/master?filepath=notebooks%2Fsymengine.ipynb for a preview

### CODE REVIEW

**Comment by certik** [comment]
The preview link on binder above works for me.

Is it better to always install from source (as you do in this PR), or should we simply install the Conda package for symengine?

One advantage of just installing the conda package is that you don't have to list all the dependencies, and you don't have to have and maintain another build script.

**Comment by isuruf** [comment]
One reason I install from source is that users will be able to check latest symengine master, otherwise they'll have to use the released v0.3.0

**Comment by SylvainCorlay** [comment]
Wow, this works! I am really excited about this (and can't wait for xeus-cling to be 100% on conda-forge). I don't have much to say about the PR. Maybe you want to add a badge at the top of the repository.

A pattern that we have found useful (but for which we will need to wait for a symengine release including the cling pragmas) is the following:

 - create a `stable` branch pointing to the latest release tag
 - have the binder link point to `https://mybinder.org/v2/gh/symengine/symengine/stable`
 - only change the `stable` branch upon releases *after* the regro-cf-autotick-bot PR is merged and built.

So that old links that you shared, and included into web pages stay current to `stable`.

**Comment by certik** [comment]
@SylvainCorlay does your workflow assume using the conda package for binder (or do you build from source like we currently do here)?

@isuruf if this is a workaround for slow releases, then we should release more often. Can you create notes of step by step instructions how to do a symengine release? I couldn't find a wiki page for that. I'll think how to optimize it, so that preferably it's just pusing a git tag, and updating the conda-forge repository.

**Comment by isuruf** [comment]
> if this is a workaround for slow releases, then we should release more often. Can you create notes of step by step instructions how to do a symengine release? I couldn't find a wiki page for that. I'll think how to optimize it, so that preferably it's just pushing a git tag, and updating the conda-forge repository.

Releasing often is not a solution (unless we do nightly releases). What I mean is that if a user wants to check latest version, they can check that. Also, if the notebooks are updated, they might not work with the last released version.

(I'll add a wiki page on how to do a symengine release. It's just pushing a .rc1 tag, checking that Python and Julia bindings work and then push the tag. conda-forge PRs are automatically done by a bot.)

**Comment by certik** [comment]
Thanks for documenting the release.

Good point about the fact that the notebook and symengine version is coupled, and so I think we have to install from source to ensure they always work. And actually I think binder might allow to specify a git hash (?) so users can check out any version they want.

So I am fine with the way it is.

**Comment by isuruf** [comment]
> And actually I think binder might allow to specify a git hash (?) so users can check out any version they want.

Yes. https://mybinder.org/v2/gh/symengine/symengine/<hash> works.

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay does your workflow assume using the conda package for binder (or do you build from source like we currently do here)?

I was assuming the conda package.

**Comment by SylvainCorlay** [comment]
An advantage of using a tag is the lesser frequent rebuild of the binder.

**Pull request merged**
