### PR TITLE
Remove whitespace

### PR DESCRIPTION
**Pull request by CodeMaxx**
@isuruf @Sumith1896

### CODE REVIEW

**Comment by abhinavagarwal07** [comment]
+1

**Comment by srajangarg** [comment]
I don't think this PR needs to be merged. The clang-format fix will deal with all these issues.

**Comment by Sumith1896** [comment]
We are currently reviewing https://github.com/symengine/symengine/pull/882
I don't break a lot in that PR by merging this. If in case we feel that #882 will take some time, we can merge this.

**Comment by Sumith1896** [comment]
Closing this as we will be moving forward with https://github.com/symengine/symengine/pull/898

**Pull request closed without merging**
