### PR TITLE
Remove Python and Ruby testing

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
Number of tests fell from 28 to 16. Added 2 tests for a total of 18.

**Comment by certik** [comment]
You'll have to resolve some conflicts.

**Comment by isuruf** [comment]
Done

**Comment by certik** [comment]
The Piranha test fails for some reason. Otherwise it seems to work.

**Comment by isuruf** [comment]
https://github.com/symengine/symengine/pull/612

**Comment by Sumith1896** [comment]
It didn't find the Boost `iostream`

**Comment by certik** [comment]
I merged that PR. Will you merge this PR with master please? That should fix it.

**Comment by isuruf** [comment]
Tests are passing now

**Comment by certik** [comment]
+1 to merge.

**Pull request merged**
