### PR TITLE
Add select declarations of matrix functions

### PR DESCRIPTION
**Pull request by ShikharJ**
This is required for https://github.com/symengine/symengine.py/pull/143

### CODE REVIEW

**Comment by isuruf** [comment]
Aren't these friend functions? Why are these needed again?

**Comment by ShikharJ** [comment]
Basically, that makes them available under the class `DenseMatrix`, but a code like this
```
symengine.col_join(deref(symengine.static_cast_DenseMatrix(self.thisptr)), deref(symengine.static_cast_DenseMatrix(o.thisptr)), deref(symengine.static_cast_DenseMatrix(result.thisptr)))
```
fails to compile giving 
```
symengine.row_join(deref(symengine.static_cast_DenseMatrix(self.thisptr)),
                               ^
symengine_wrapper.pyx:1802:32: Cannot convert 'DenseMatrix' to Python object
```
The only other alternative that appeared to me was to `cdef` another copy of `self` and then passing it on to the function.

**Comment by isuruf** [comment]
I think that's an issue that has to be fixed in symengine.py. not here.

**Comment by ShikharJ** [comment]
I'll close it up then. Can you please cancel these builds?

**Pull request closed without merging**
