### PR TITLE
Stop building teuchos when not needed

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
That looks, good. +1 if tests pass.

**Comment by isuruf** [comment]
Coveralls check is not showing up. @certik, did you make any changes to the settings?

**Comment by certik** [comment]
No, didn't touch a thing. I checked, it seems it's enabled. Maybe it needs more time, or perhaps it actually only shows after Travis finishes?

**Comment by isuruf** [comment]
Can you try login out and login back again? There may be authentication issues

**Pull request merged**
