### PR TITLE
Use nifty counter idiom for SIOF

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/symengine/symengine/issues/2057

### CODE REVIEW

**Review by oliverlee — COMMENTED** [review]
Nice! 

Does this PR add a regression test?

aligned_storage is deprecated and should never be used. You can use an anonymous union with a single type instead.
 https://stackoverflow.com/questions/71828288/why-is-stdaligned-storage-to-be-deprecated-in-c23-and-what-to-use-instead

**Comment by bjodah** [comment]
For regression testing, we can replace our use of `expand1.cpp` here:
https://github.com/symengine/symengine/blob/3d8627517912e58d12822645575f87d28b7f0cf3/bin/test_travis.sh#L211

with a `.cpp` based on @oliverlee's example in gh-2057 perhaps?

**Comment by certik** [comment]
So the way this works is:

* Every translation unit gets its own `constantInitializer`
* When the translation unit gets created (in any order), the `constantInitializer` increments a global counter
* The global symengine constants are now references, and we allocate them exactly once, using the global counter
* If `constantInitializer`'s destructor every gets called (not sure if that happens?), we free the global symengine expressions, exactly once.

I think this can work! Thanks @isuruf for implementing it.

**Review by bjodah — APPROVED** [review]
Looks great!

**Review by certik — APPROVED** [review]
I think this looks good. Is my understanding at https://github.com/symengine/symengine/pull/2059#issuecomment-2440202970 correct?

**Comment by isuruf** [comment]
> Is my understanding at https://github.com/symengine/symengine/pull/2059#issuecomment-2440202970 correct?

Yep. 

>  (not sure if that happens?)

It gets called when each translation unit gets unloaded and when all translation units are unloaded, the expression is freed. This happens when the program terminates or if we opened the library using `dlopen`, it happens when the library is closed via `dlclose`.

**Comment by certik** [comment]
@isuruf excellent. (I wasn't sure if this happens when the program terminates, since the OS cleans the memory anyway.)

**Pull request merged**
