### PR TITLE
Update catch (support -std=c++17)

### PR DESCRIPTION
**Pull request by bjodah**
As the commit message says, support for std=c++17
random_shuffle was removed from std:: in c++17 (deprecated in c++14).

Excerpt from symengine build:
```
[ 41%] Building CXX object symengine/utilities/catch/CMakeFiles/catch.dir/catch.cpp.o
cd /conda-bld/symengine_1524567697988/work/build/symengine/utilities/catch && /conda-bld/symengine_1524567697988/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/clang++   -I/conda-bld/symengine_1524567697988/work -I/conda-bld/symengine_1524567697988/work/build -isystem /conda-bld/symengine_1524567697988/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include  -DBOOST_MATH_DISABLE_FLOAT128 -m64 -O2 -stdlib=libc++ -std=c++17 -fPIC -D__extern_always_inline=inline -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DNDEBUG -Wno-unknown-pragmas   -o CMakeFiles/catch.dir/catch.cpp.o -c /conda-bld/symengine_1524567697988/work/symengine/utilities/catch/catch.cpp
In file included from /conda-bld/symengine_1524567697988/work/symengine/utilities/catch/catch.cpp:6:
/conda-bld/symengine_1524567697988/work/symengine/utilities/catch/catch.hpp:5805:26: error: no member named 'random_shuffle' in namespace 'std'
                    std::random_shuffle( matchingTestCases.begin(), matchingTestCases.end(), rng );
                    ~~~~~^
1 error generated.
```

### CODE REVIEW

**Comment by certik** [comment]
Any idea why the code coverage reports this: https://codecov.io/gh/symengine/symengine/compare/75dd6e58bab20569258f640ba55324daf261bcc1...15aeb289f4e9806ad3b4affc814b249150b21475/src/symengine/polys/uexprpoly.h and fails?

**Comment by bjodah** [comment]
I haven't looked into it in depth, I just assumed that it got "pretty printed" somewhere in the tests with the earlier version of catch. I could add a test using a stringstream and calling `.str`?

**Comment by certik** [comment]
If you wouldn't mind adding a test using `.str`, that would be great. I am +1 to merge this, even as is, but the test would help.

**Comment by certik** [comment]
Thanks. I don't know why the code coverage test fails. +1 to merge.

**Pull request merged**
