### PR TITLE
[skip ci] Update AUTHORS

### PR DESCRIPTION
**Pull request by isuruf**
@RiteshKB, @ShikharJ, @vishusidana95 can you check that the names are correct in AUTHORS file? If not let me know.

### CODE REVIEW

**Comment by ShikharJ** [comment]
@isuruf I'm on it.

**Comment by vishusidana95** [comment]
@isuruf yeah that looks fine.

**Comment by RiteshKB** [comment]
@isuruf  can you change **Ritesh Kumar** instead of **comperror** and can add in .mailmap file

**Comment by RiteshKB** [comment]
@isuruf  can you please change **comperror** to **RiteshKB** in .mailmap file

**Comment by isuruf** [comment]
@RiteshKB, it is changed.

**Comment by certik** [comment]
Thanks @isuruf.

**Pull request merged**
