### PR TITLE
Compiler independent hashing

### PR DESCRIPTION
**Pull request by isuruf**
This makes the hashing independent of the compiler although it depends on the size of `size_t` which means there is a difference when it comes to 32-bit and 64-bit.

### CODE REVIEW

**Comment by isuruf** [comment]
Since we are using C++11, I'm using `uint64_t` as the hash value size. This should make the printing compiler independent across platforms.

**Comment by srajangarg** [comment]
+1, this will fix the multivariate polynomial printing too right?

**Comment by certik** [comment]
How is speed affected by this PR?

**Comment by isuruf** [comment]
Only speed penalty is with hashing of `Symbol`s, but that's a very low overhead for all of the benchmarks. It's negligible since the hash is cached.

**Comment by certik** [comment]
@isuruf ok, then I am +1 to merge.

**Pull request merged**
