### PR TITLE
Added Ralf, Indrek, Abhinav, Akash, Srajan and Abhimanyu to AUTHORS. …

### PR DESCRIPTION
**Pull request by isuruf**
…Welcome to SymEngine!

### CODE REVIEW

**Comment by isuruf** [comment]
@rwst, @harakas, @abhinavagarwal07, @CodeMaxx , @srajangarg, @abhimanyu-siwach, let me know if there needs to be any change

**Comment by abhinavagarwal07** [comment]
Thanks @isuruf

**Comment by rwst** [comment]
Very good.

**Comment by CodeMaxx** [comment]
Thanks @isuruf

**Pull request merged**
