### PR TITLE
add visitor_call benchmark

### PR DESCRIPTION
**Pull request by lkeegan**
- benchmark `call()` for
    - `LambdaRealDoubleVisitor`: with/without CSE
    - `LLVMDoubleVisitor`: O0-O3, with/without CSE
    - `LLVMFloatVisitor`: O0-O3, with/without CSE
    - `NativeVisitor`: just calls pre-compiled c++ function (only defined in this benchmark)
  - uses Google Benchmark: added as a git submodule
  - remove `bench_lambda_double benchmark`

### CODE REVIEW

**Comment by lkeegan** [comment]
`./benchmarks/visitor_call` sample output:
```
-------------------------------------------------------------------------------------------
Benchmark                                                 Time             CPU   Iterations
-------------------------------------------------------------------------------------------
Call<LambdaRealDoubleVisitor, Expr1, double>/0/0        908 ns          908 ns       827788
Call<LambdaRealDoubleVisitor, Expr1, double>/1/0        276 ns          276 ns      2556336 cse
Call<LLVMDoubleVisitor, Expr1, double>/0/0              363 ns          363 ns      1945164 O0
Call<LLVMDoubleVisitor, Expr1, double>/1/0              124 ns          124 ns      5737308 cse_O0
Call<LLVMDoubleVisitor, Expr1, double>/0/1              122 ns          122 ns      5827584 O1
Call<LLVMDoubleVisitor, Expr1, double>/1/1              122 ns          122 ns      5828941 cse_O1
Call<LLVMDoubleVisitor, Expr1, double>/0/2              122 ns          122 ns      5827364 O2
Call<LLVMDoubleVisitor, Expr1, double>/1/2              122 ns          122 ns      5825523 cse_O2
Call<LLVMDoubleVisitor, Expr1, double>/0/3              122 ns          122 ns      5826689 O3
Call<LLVMDoubleVisitor, Expr1, double>/1/3              122 ns          122 ns      5825476 cse_O3
Call<NativeVisitor<double>, Expr1, double>/0/0          121 ns          121 ns      5857892
Call<LLVMFloatVisitor, Expr1, float>/0/0               82.2 ns         82.2 ns      8593947 O0
Call<LLVMFloatVisitor, Expr1, float>/1/0               43.2 ns         43.2 ns     16066797 cse_O0
Call<LLVMFloatVisitor, Expr1, float>/0/1               43.7 ns         43.7 ns     15930059 O1
Call<LLVMFloatVisitor, Expr1, float>/1/1               43.7 ns         43.7 ns     15886179 cse_O1
Call<LLVMFloatVisitor, Expr1, float>/0/2               43.8 ns         43.8 ns     15913577 O2
Call<LLVMFloatVisitor, Expr1, float>/1/2               43.6 ns         43.6 ns     15863667 cse_O2
Call<LLVMFloatVisitor, Expr1, float>/0/3               43.6 ns         43.6 ns     15943914 O3
Call<LLVMFloatVisitor, Expr1, float>/1/3               43.6 ns         43.6 ns     15941080 cse_O3
Call<NativeVisitor<float>, Expr1, float>/0/0           41.8 ns         41.8 ns     16630481
Call<LambdaRealDoubleVisitor, Expr2, double>/0/0        214 ns          214 ns      3269388
Call<LambdaRealDoubleVisitor, Expr2, double>/1/0        114 ns          114 ns      6067488 cse
Call<LLVMDoubleVisitor, Expr2, double>/0/0             8.43 ns         8.43 ns     83012254 O0
Call<LLVMDoubleVisitor, Expr2, double>/1/0             8.43 ns         8.43 ns     83019707 cse_O0
Call<LLVMDoubleVisitor, Expr2, double>/0/1             8.43 ns         8.43 ns     83020859 O1
Call<LLVMDoubleVisitor, Expr2, double>/1/1             8.43 ns         8.43 ns     83044566 cse_O1
Call<LLVMDoubleVisitor, Expr2, double>/0/2             8.43 ns         8.43 ns     82980459 O2
Call<LLVMDoubleVisitor, Expr2, double>/1/2             8.43 ns         8.43 ns     82982062 cse_O2
Call<LLVMDoubleVisitor, Expr2, double>/0/3             8.44 ns         8.43 ns     82999153 O3
Call<LLVMDoubleVisitor, Expr2, double>/1/3             8.43 ns         8.43 ns     83024157 cse_O3
Call<NativeVisitor<double>, Expr2, double>/0/0         8.18 ns         8.17 ns     85649992
Call<LLVMFloatVisitor, Expr2, float>/0/0               5.28 ns         5.28 ns    133473722 O0
Call<LLVMFloatVisitor, Expr2, float>/1/0               4.77 ns         4.77 ns    146885508 cse_O0
Call<LLVMFloatVisitor, Expr2, float>/0/1               5.27 ns         5.26 ns    132642732 O1
Call<LLVMFloatVisitor, Expr2, float>/1/1               5.24 ns         5.24 ns    133163999 cse_O1
Call<LLVMFloatVisitor, Expr2, float>/0/2               5.26 ns         5.26 ns    132179120 O2
Call<LLVMFloatVisitor, Expr2, float>/1/2               5.26 ns         5.26 ns    133184573 cse_O2
Call<LLVMFloatVisitor, Expr2, float>/0/3               5.25 ns         5.25 ns    133705161 O3
Call<LLVMFloatVisitor, Expr2, float>/1/3               5.24 ns         5.23 ns    132832492 cse_O3
Call<NativeVisitor<float>, Expr2, float>/0/0           4.95 ns         4.95 ns    141549861
```

**Review by certik — APPROVED** [review]
Thanks for the PR.

I am not a big fan of submodules, but if @isuruf is fine with it, I am ok.

@isuruf would you mind reviewing this PR please?

**Comment by lkeegan** [comment]
@certik I'd be happy to change the submodule - what would you rather do? the two alternatives I am aware of are:
1. just copy the google benchmark code to your repo
2. have cmake download it with `ExternalProject` (something like https://crascit.com/2015/07/25/cmake-gtest/)

**Comment by isuruf** [comment]
How about using it externally as in https://github.com/google/benchmark#usage-with-cmake? I'm not a fan of git submodule either. I'd like to avoid having to create tarballs for a release since the github provided tarball doesn't include git submodules.

**Review by isuruf — APPROVED** [review]

**Pull request merged**
