### PR TITLE
Add Sam to AUTHORS and update emails

### PR DESCRIPTION
**Pull request by isuruf**
@thesamesam, let me know if your email and name are correct.

@PerformanceCoder, fixed now. Can you check if it's correct?

### CODE REVIEW

**Comment by isuruf** [comment]
@bocklund, do you prefer the gmail or the llnl email?

**Comment by bocklund** [comment]
> @bocklund, do you prefer the gmail or the llnl email?

Please prefer the gmail first. Keeping both in gmail, then LLNL is fine with me if possible. 

Thanks!

**Review by thesamesam — APPROVED** [review]
Thanks!

**Comment by isuruf** [comment]
> Please prefer the gmail first. Keeping both in gmail, then LLNL is fine with me if possible.

I'm not sure I understand. We use one email in AUTHORS and it can be either the gmail one or llnl one.

**Comment by bocklund** [comment]
Sorry I saw the mailmap and authors in the diff and wasn’t sure which you were asking for. Please use my gmail for authors.

**Comment by isuruf** [comment]
No worries. Thanks for confirming

**Pull request merged**
