### PR TITLE
Exposed some query methods

### PR DESCRIPTION
**Pull request by anutosh491**

### CODE REVIEW

**Review by isuruf — COMMENTED** [review]
Why do we need these methods and just 5 of them?
It's a simple one liner `basic_get_type(s) == SYMENGINE_ADD`.

**Comment by certik** [comment]
I agree, I think `basic_get_type(s) == SYMENGINE_ADD` seems good enough to me.

**Comment by anutosh491** [comment]
I think so here we would only need the ` basic_is_Exp` function because I don't we have something like 
`basic_get_type(s) == SYMENGINE_EXP`
The type of `s` would still be `Pow`, we would just need to check it's base against E

**Comment by certik** [comment]
Why couldn't we do `basic_get_type(s) == SYMENGINE_EXP` in LPython?

**Comment by anutosh491** [comment]
Because I don't think we have a defined `SYMENGINE_EXP` class type registered here (https://github.com/symengine/symengine/blob/master/symengine/type_codes.inc)

**Comment by certik** [comment]
EXP I think is represented as just Power with a base E.

**Pull request closed without merging**
