### PR TITLE
add override (clang-modernize 3.7)

### PR DESCRIPTION
**Pull request by rwst**

### CODE REVIEW

**Comment by isuruf** [comment]
+1

**Comment by certik** [comment]
Is the idea to put `override` every time you implement a virtual function?

**Comment by rwst** [comment]
@certik yes to show the intent, to avoid the first scenario in https://en.wikipedia.org/wiki/C%2B%2B11#Explicit_overrides_and_final, and to prepare for future optimizations.

**Comment by certik** [comment]
Cool. I like that.

**Pull request merged**
