### PR TITLE
Make EvalDoubleVisitor::apply and result_ visible to EvalRealDoubleVisitor

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@rwst, tests pass

**Comment by Sumith1896** [comment]
Tests pass, current master is failing, I'm merging this.

**Comment by Sumith1896** [comment]
Thanks @isuruf

**Comment by certik** [comment]
@isuruf thanks for fixing it.

**Comment by rwst** [comment]
Thanks too.

**Pull request merged**
