### PR TITLE
WIP: use bison instead of bisonc++

### PR DESCRIPTION
**Pull request by certik**
This was a lot of work to get this working. It's still hackish, but at least it runs now and it seems to be much faster.

TODO:
* [x] use reentrant parser
* [x] remove the bisonc++ parser, make this parser the default, pass all tests with this new parser
* [x] Fix `symengine/parser/parser_new.h:27:10: error: 'unique_ptr' in namespace 'std' does not name a template type` (https://travis-ci.org/symengine/symengine/jobs/567605926)
* [x] FIx `parser.tab.cc:405:56: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ writing to an object of type ‘YYSTYPE’ {aka ‘struct YYSTYPE’} with no trivial copy-assignment;` (https://travis-ci.org/symengine/symengine/jobs/567605913)
* [x] The `parse()` function segfaults on Windows in mingw (https://ci.appveyor.com/project/symengine/symengine/builds/26460875/job/malif7b0jglpfodr)
* [x] polish the PR

Further speedups are [possible](https://github.com/symengine/symengine/pull/1590#issuecomment-517979882) but those should be done in another PR once this is merged.

### CODE REVIEW

**Comment by certik** [comment]
I am getting 19ms for the benchmark.

**Comment by certik** [comment]
I can't believe how much faster this is. And there are further speedups possible. First one should not create `std::string` for the tokens at all, but rather convert integers / floats directly in the tokenizer quickly. Variables and function names could for now be passed as `std::string`, although something like `std::string_view` (C++17) might be even faster.

/cc @isuruf.

**Comment by certik** [comment]
Travis passed in 71e29d7ec2487bf263c3b97364f707678726a6e1 with a temporary fix. Hopefully it passes now too, with the proper fix.

Windows still segfaults, it will have to be debugged. I think first I'll make the parser reentrant, which should greatly simplify all the hacks I had to do and clean up the code. Then it should be easier to debug the Windows issue.

**Comment by certik** [comment]
I noticed a performance regression on the repeated benchmark from 20ms to 56ms. git bisect shows it's caused by the 9b6e6190f88ded7b98d7ded8ed2250b26cc937b6 commit.

**Comment by certik** [comment]
I see. Starting at 9b6e6190f88ded7b98d7ded8ed2250b26cc937b6 and making the change:
```diff
--- a/symengine/parser/parser_new.cpp
+++ b/symengine/parser/parser_new.cpp
@@ -7,9 +7,10 @@
 namespace SymEngine
 {
 
+Parser2 p;
+
 RCP<const Basic> parse(const std::string &s, bool convert_xor)
 {
-    Parser2 p;
     p.init(s, convert_xor);
     // TODO: check how sval is handled
     // yy::tokenizer.sval = &p.sval;
```
The timing goes down to 27ms. Still slower than 20-22ms, but it shows that what the Parser2 class is doing is expensive (it must be all the initialization of the maps and dictionaries).

**Comment by certik** [comment]
Looks like the Windows failure fixed itself! Nice. I suspect it had to do with some global variables that must be exported differently on Windows.

**Comment by isuruf** [comment]
> (it must be all the initialization of the maps and dictionaries).

Master also has these and if I make the parser a global object in master, benchmark doesn't change. There must be something in the new parser that is expensive to initialize.

**Comment by certik** [comment]
The speed issue is now fixed.

**Comment by certik** [comment]
> > (it must be all the initialization of the maps and dictionaries).
> 
> Master also has these and if I make the parser a global object in master, benchmark doesn't change. There must be something in the new parser that is expensive to initialize.

They do change in master also. Take the latest master (c66b8c50bb481c51ce128b768b056454aa6dc67a), apply the following patch:
```diff
diff --git a/symengine/parser/parser.cpp b/symengine/parser/parser.cpp
index 336d8489..05f5dc79 100644
--- a/symengine/parser/parser.cpp
+++ b/symengine/parser/parser.cpp
@@ -53,6 +53,11 @@
 // const. If --thread-safe is not provided, the state-tables are not defined
 // as const, since the lookup() function below will modify them
 
+namespace SymEngine
+{
+Parser p;
+}
+
 namespace // anonymous
 {
 
diff --git a/symengine/parser/parser.h b/symengine/parser/parser.h
index 8e3404e8..512f9c77 100644
--- a/symengine/parser/parser.h
+++ b/symengine/parser/parser.h
@@ -14,7 +14,7 @@ class Parser : public ParserBase
 public:
     RCP<const Basic> res;
 
-    inline Parser(const std::string &input, bool convert_xor_)
+    void init(const std::string &input, bool convert_xor_)
     {
         inp = input;
         if (convert_xor_) {
diff --git a/symengine/parser/parser.ih b/symengine/parser/parser.ih
index ebb685bd..1a39f14f 100644
--- a/symengine/parser/parser.ih
+++ b/symengine/parser/parser.ih
@@ -15,9 +15,11 @@ inline void Parser::print()
     print__(); // displays tokens if --print was specified
 }
 
+extern Parser p;
+
 RCP<const Basic> parse(const std::string &s, bool convert_xor)
 {
-    Parser p(s, convert_xor);
+    p.init(s, convert_xor);
 
     if (p.parse() == 0)
         return p.res;
```
and run benchmarks. Before the patch:
```
$ ./benchmarks/parsing 
54ms
(x + y - sin(x)/(-4 + z**2) - x**(y**z))**5001
84ms
(x + y - sin(x)/(-4 + z**2) - x**(y**z))**5001
77ms
101ms
```
after the patch:
```
$ ./benchmarks/parsing 
56ms
(x + y - sin(x)/(-4 + z**2) - x**(y**z))**5001
83ms
(x + y - sin(x)/(-4 + z**2) - x**(y**z))**5001
42ms
100ms
```
You can see the second benchmark got faster by 35ms. Which is exactly the same speedup I have observed in this PR with the new parser. The cost of initializing Parser is  35ms.

**Comment by certik** [comment]
All tests pass here.

Closing in favor of #1591.

**Pull request closed without merging**
