### PR TITLE
Simplify abs(abs(x))

### PR DESCRIPTION
**Pull request by mydatamodels**
As discussed on gitter with @isuruf (I was @torshind_gitlab).

### CODE REVIEW

**Comment by isuruf** [comment]
Thanks for the PR

**Comment by certik** [comment]
Thanks. This looks simple enough to merge. However, would should be the guideline to determine which simplifications to do automatically and which to do as part of "simplify" or other functionality that operates on the SymEngine expression tree?

**Comment by isuruf** [comment]
For functions, I would say, do any fast operations that result in a simpler expression. So, `abs(abs(x))` should be simplified to `abs(x)` as the check is fast and results in a simpler expression. `tan(pi/24)` -> `-2 + sqrt(6) - sqrt(5 - 2 sqrt(6))` is fast, but not simpler and therefore we don't do it. `cos(asin(x/sqrt(x^2+y^2)))` -> `sqrt(1 - x^2/(x^2 + y^2))` is simpler, but not fast to check.

**Comment by certik** [comment]
@isuruf perfect!  I vaguely remember I was arguing exactly what you wrote some time ago, but forgot. So I documented it at https://github.com/symengine/symengine/wiki/Simplifications-Guidelines.

**Pull request merged**
