### PR TITLE
Moved the catch and teuchos dir to symengine/utilities

### PR DESCRIPTION
**Pull request by CodeMaxx**
For #711

### CODE REVIEW

**Comment by Sumith1896** [comment]
@CodeMaxx You just have to move the files, I think you have recommitted them.

**Comment by Sumith1896** [comment]
Something like this from the base directory
```
mv symengine/catch symengine/utilities/
git rm -r symengine/catch
git add symengine/utilities/catch
```
Similarly for `teuchos` and then commit

**Comment by CodeMaxx** [comment]
I hope its correct this time

**Comment by Sumith1896** [comment]
It's correct.
Let's wait for @certik's opinion on this.

**Comment by CodeMaxx** [comment]
Travis says some files not found but they are present

**Comment by Sumith1896** [comment]
Maybe https://github.com/CodeMaxx/symengine/blob/54a4f60e3446a4cd41f70e548396b913774637aa/symengine/utilities/teuchos/CMakeLists.txt#L59 is causing it?

**Comment by CodeMaxx** [comment]
@Sumith1896  Thanxx . Its working now.

**Comment by certik** [comment]
+1 to merge. @CodeMaxx would you mind merging the latest master into this? I would like to make sure that things still work with the latest master, as I merged some other PRs in the meantime.

**Comment by CodeMaxx** [comment]
@certik Merged the latest master.

**Comment by certik** [comment]
It looks like it is working, merging. Thanks @CodeMaxx !

**Comment by Sumith1896** [comment]
Thanks @CodeMaxx :)

**Comment by CodeMaxx** [comment]
Thanx for the merge!

**Pull request merged**
