### PR TITLE
could_extract_minus handles x-y and y-x

### PR DESCRIPTION
**Pull request by vyasgiridhar**
#871 
Can be used for abs(y-x) == abs(x-y).

### CODE REVIEW

**Comment by CodeMaxx** [comment]
Hi @vyasgiridhar Welcome to SymEngine! 
So there's a problem with your code. Though the issue didn't mention it properly but we are looking to differentiate between all such expressions as `x-y-z` and `z+y-x` and not just for the special case of `x-y`.

**Comment by vyasgiridhar** [comment]
this works out?

**Comment by CodeMaxx** [comment]
No. What exactly are you trying to do? You are getting segmentation faults as well.

**Comment by vyasgiridhar** [comment]
Solved the segmentation faults.

**Comment by CodeMaxx** [comment]
You should add more tests to check if your code works.

**Pull request closed without merging**
