### PR TITLE
Ubuntu 20.04 for msan & ubsan tests (llvm-12)

### PR DESCRIPTION
**Pull request by bjodah**
Trying to get msan to work (as an alternative to #1820)

### CODE REVIEW

**Comment by rikardn** [comment]
Thanks @bjodah for working on this. This is the proper way of fixing the sanitizer problems.

I noticed the remaining error is referring to `enable_if_t` which is a feature from C++14. Could it be that the compiler or the stdlib is set to C++11?

**Comment by bjodah** [comment]
Probably, thanks! Let's see if it builds with c++20 (would be nice to have that tested too).

**Comment by rikardn** [comment]
Now we get this:

```
cd /home/runner/work/symengine/symengine/build/symengine && /usr/bin/clang++  -Dsymengine_EXPORTS -I/home/runner/work/symengine/symengine -I/home/runner/work/symengine/symengine/build -I/home/runner/work/symengine/symengine/build/symengine/utilities/teuchos -I/home/runner/work/symengine/symengine/symengine/utilities/teuchos -isystem /home/runner/our_usr/include  -std=c++11 -std=c++20 -fPIC -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -Wno-unused-parameter -g -ggdb -Wno-unknown-pragmas   -Wconversion -Wno-sign-conversion -Qunused-arguments -include /home/runner/work/symengine/symengine/build/symengine/cotire/symengine_CXX_prefix.hxx -std=c++14 -o CMakeFiles/symengine.dir/add.cpp.o -c /home/runner/work/symengine/symengine/symengine/add.cpp
error: C++17 was enabled in PCH file but is currently disabled
```

Seems to be three `-std` options on that line.

**Comment by bjodah** [comment]
yay.... :-/
I seem to remember having to disable cotire too.

**Review by rikardn — APPROVED** [review]
And it works! I think this could be squashed and merged now.

**Comment by bjodah** [comment]
Thanks!

**Pull request merged**
