### PR TITLE
Added rational_get_mpq

### PR DESCRIPTION
**Pull request by ShikharJ**
Yet to write the tests for the above function. Some features for #1088 are yet to be added.

### CODE REVIEW

**Comment by certik** [comment]
I think that looks good. @isuruf ?

**Comment by isuruf** [comment]
Can you add a test? We can merge after that

**Comment by ShikharJ** [comment]
@isuruf Two builds failed on travis. One due to formatting issues, and the other due to timeout. I will first work on these, and then add a test (I am new to these functions, so that may take some time).

**Comment by isuruf** [comment]
Ignore the second timeout. That's an issue with Travis. 
See this about formatting code locally, https://github.com/symengine/symengine/wiki/Development-workflow-for-SymEngine

**Comment by ShikharJ** [comment]
@isuruf In that case, any guidance regarding implementing test cases?

**Comment by isuruf** [comment]
It can be a very simple one. Create a basic `b = 2`, divide it by `4`,  extract the mpq and check that it is equal to `1/2`

**Comment by ShikharJ** [comment]
@isuruf I believe some undesired changes have occured while amending. I'll create a fresh pull request along with the tests.

**Comment by isuruf** [comment]
You can force push to this branch so that you don't need to close and open a fresh PR

**Comment by ShikharJ** [comment]
I did that, still my local repository is showing some weird changes.

**Pull request closed without merging**
