### PR TITLE
Refactor subs into a visitor and add msubs

### PR DESCRIPTION
**Pull request by isuruf**
msubs is to be used as a replacement for `sympy.physics.mechanics.functions.msubs`
Depends on #923

### CODE REVIEW

**Comment by isuruf** [comment]
@certik, ping

**Comment by certik** [comment]
This is +1, great job. 

Is there any performance penalty for this PR?

**Comment by isuruf** [comment]
Theoretically yes, but I ran `expand6` and timed the subs step. There's no visible change.

**Comment by certik** [comment]
Ok, then I think it's fine to merge this.

**Pull request merged**
