### PR TITLE
Don't revisit in CountOpsVisitor

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
Can you please describe briefly what this is trying to fix or how it works? (Next time you can do it in the git commit, that way it is documented for others in the git history.)

**Comment by isuruf** [comment]
Sure. In this visitor, already seen nodes are stored in an `unordered_map` with the op count and if the node is visited again, the previously computed value is used.

**Comment by certik** [comment]
I see. Yes, then this looks good. But why would the same node be visited twice?

**Comment by isuruf** [comment]
If the expression is like, `sin(x) + 1/sin(x)`, then `sin(x)` is visited twice.

**Comment by certik** [comment]
Ah I see. Got it. Thanks!

**Comment by isuruf** [comment]
Thanks for the review

**Pull request merged**
