### PR TITLE
Add Anubhav, Rikard, Will, myd7340, Fabian, Rohit to AUTHORS.

### PR DESCRIPTION
**Pull request by isuruf**
@rikardn, @myd7349, @HaoZeke, @sudoWin, @Marlin-Na, @willsimmons1465, @f-koehler, let me know whether your preferred name and email is in the AUTHORS file and if not I'll change it.

### CODE REVIEW

**Comment by rikardn** [comment]
Thanks for adding me! The domain in my email has changed to ```@farmaci.uu.se```

**Comment by f-koehler** [comment]
I am: Fabian Köhler <fabian.koehler@protonmail.ch>
Thanks for adding me, even though my contribution is fairly minor

**Comment by HaoZeke** [comment]
Thanks for adding me! It looks great.

**Comment by sudoWin** [comment]
Thanks for adding me 😄

**Comment by isuruf** [comment]
@myd7349, @Marlin-Na, @willsimmons1465, I'm going to merge this PR for the release, but please let me know if there's any change needed and we can change after the release.

**Pull request merged**
