### PR TITLE
fix trig function having a multiple of pi/3, p/4, pi/6, pi/12; fixes …

### PR DESCRIPTION
**Pull request by rwst**
…#1035

### CODE REVIEW

**Comment by rwst** [comment]
The problem (apart from the incompleteness) was that the original author returned the wrong expression for unhandled cases in `eval()`s `rarg`. Returning the right thing however was impossible unless the canonical check was made less stringent, else an infinite loop occurred.

**Comment by certik** [comment]
Thanks @rwst for fixing it! I need to go over your code more carefully.

**Comment by isuruf** [comment]
@rwst, I have some improvements to this PR. Can you enable `Allow edits from maintainers` for this PR? (There should be a tick box in the right side bar)

**Comment by rwst** [comment]
Please go ahead.

**Comment by isuruf** [comment]
@certik, @rwst, can you review?

**Comment by isuruf** [comment]
Change I've made is to reduce `sin(r*pi + x)`  to the first quadrant for any `r` rational number.

**Comment by certik** [comment]
I think that looks good to me.

How are benchmarks with trigonometric functions affected?

**Comment by isuruf** [comment]
We don't have any that uses the code paths changed in this PR. Only simple arguments like `x` are used for trig functions

**Comment by certik** [comment]
I see, thanks. +1 to merge then.

**Pull request merged**
