### PR TITLE
Support symbols in evalf

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/symengine/symengine/issues/1488

### CODE REVIEW

**Comment by isuruf** [comment]
Ready for review

**Comment by bjodah** [comment]
+1
I guess a leading underscore is ok since it's followed by a non-capital letter and it is not in the global scope?

Do we expect that no one would want to call the older version of evalf (which is now called `_evalf`)? (an alternative would perhaps to name it "evalf_symbol_free" or something).

**Comment by isuruf** [comment]
Thanks for the review

**Comment by isuruf** [comment]
Thanks for the review

**Pull request merged**
