### PR TITLE
Remove -march=native in UserOverride.cmake

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
> I thought this was already done.

Me too. Last PR I sent missed this.

**Comment by bjodah** [comment]
I sometimes build with boost 1.70:
```
CC=gcc-8   CXX=g++-8 CXXFLAGS="-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -fsized-deallocation" /opt/get_symengine.sh ab7c16a5df4ee8688d0a990d0f09f5cb510e69f2 /opt/symengine-ab7c16a-dbg Debug   -DWITH_BFD=ON  -DINTEGER_CLASS=boostmp
```

where `get_symengine.sh` is from here:
https://github.com/bjodah/bjodahimg18dev/blob/master/environment/scripts/get_symengine.sh

don't know if that helps...

**Comment by isuruf** [comment]
I want to check with the oldest compiler we support and newer boost in conda-forge are compiled with newer gcc and the old boost versions which were compiled with an older compiler are not installable anymore.

**Comment by certik** [comment]
@isuruf since Boost is an optional dependency, I am fine with requiring whatever compiler Conda is using. We can just have a test for the core of symengine without any optional dependencies that uses an old compiler.

Looks like right now we require at least gcc 4.7? That was released March 2012, which is over 7 years ago. I think we should support all gcc compilers released in the last 5 years. So that would be gcc 4.9 or newer. I don't know if we should support more than 5 years, it seems 5 should be enough.

**Comment by isuruf** [comment]
We need to support gcc 4.8 for manylinux1 wheels until manylinux1 is superceded by manylinux2010

**Comment by certik** [comment]
I see, yes. I forgot to add: I think the rule is "last 5 years" and any older gcc that is used in platforms we want to support like Debian of certain version, Ubuntu, and manylinux1.

**Pull request closed without merging**
